In [1648]:
import pandas as pd
from datetime import datetime, date, timedelta
from faker import Faker
from faker.providers import BaseProvider
from sqlalchemy import create_engine
import random

Importing spreadsheets created

In [1649]:
amr_df = pd.read_excel("TrialDummy1.xlsx")
amr_df

,amrID,supplierID,year,assignedBy,assignedDate,destinationOfSample,submittedDate,amountAvailable,synthesisPotential,sourceID,...,solubility,stereoComments,smileStructure,mw,additionalMetadata,existingPatent,existingLiterature,solvent,sampleType,comments
0,AMR00001,AAP_1,2048,Ruby Johnson,08/10/2053,Rhodes MS,01/10/2053,16.3,NaN,AAP_1,...,NaN,NaN,NaN,NaN,N,N,https//doi.org/choice4,Methanol,NaN,NaN
1,AMR00002,MOZ42-1JR,2042,Joshua Keener,06/01/2051,Rhodes MS,30/12/2050,49.9,NaN,MOZ42-1,...,NaN,NaN,NaN,NaN,Y,N,https//doi.org/choice6,DMSO,NaN,NaN
2,AMR00003,TIC2041-1RH,2041,Ruby Johnson,31/01/2050,Rhodes MS/NMR,24/01/2050,94.0,NaN,TIC2041-1,...,NaN,NaN,NaN,NaN,N,N,Y,DMSO,NaN,NaN
3,AMR00004,MOZ42-2JR,2042,Ruby Johnson,16/10/2050,Rhodes MS/NMR,09/10/2050,95.0,NaN,MOZ42-2,...,NaN,NaN,NaN,NaN,N,N,Y,DMSO,NaN,NaN
4,AMR00005,TIC2041-2JR,2041,Joshua Keener,21/12/2054,"Rhodes Bioassay, PK assay",14/12/2054,14.0,NaN,TIC2041-2,...,NaN,NaN,NaN,NaN,N,N,Y,DMSO,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,AMR00156,PC-AMRU3B-02bbd,2045,Ruby Johnson,09/04/2051,Rhodes LC/MS + NMR & Bioassay,02/04/2051,18.4,Y,AMRU3B-02bb,...,"aq.MeOH, MeOH",InterestPC6,citizen,324.3,N,Y,https://doi.org/comp4,DCM:MeOH 2:1,Fraction from flash,NaN
156,AMR00157,PC-AMRU7B-02aaa,2045,Joshua Keener,06/05/2051,Membrane Disruption assay,29/04/2051,11.4,N,AMRU7B-02aa,...,DCM: MeOH 2:1,InterestPC3,treatment,70.9,Y,Y,Y,DCM/MeOH,HPLC Fraction,Used compound Q in fractionation
157,AMR00158,PC-AMRU3B-02bba,2045,Ruby Johnson,09/04/2051,"Rhodes Bioassay, PK assay",02/04/2051,45.6,N,AMRU3B-02bb,...,DMSO,InterestPC6,size,26.9,Y,Y,https://doi.org/comp1,DCM:MeOH 2:1,Fraction from flash,NaN
158,AMR00159,PC-MOZ42-13RH-01aba,2042,Joshua Keener,29/04/2055,Rhodes MS,22/04/2055,83.1,N,MOZ42-13RH-01ab,...,DMSO,InterestPC7,live,64.1,Y,Y,https://doi.org/comp3,DCM:MeOH 2:1,SPE fraction,NaN
159,AMR00160,PC-1-1*#1R3-01caa,2046,Ruby Johnson,24/11/2052,Rhodes MS,17/11/2052,41.6,Y,1-1*#1R3-01ca,...,DCM: MeOH 2:1,InterestPC4,car,23.2,Y,N,N,MeOH,Fraction from flash,NaN

In [1650]:
extract_df = amr_df[amr_df['pure'] == "N"].reset_index()
pure_df = amr_df[amr_df['pure'] == "Y"].reset_index()
extract_df

,index,amrID,supplierID,year,assignedBy,assignedDate,destinationOfSample,submittedDate,amountAvailable,synthesisPotential,...,solubility,stereoComments,smileStructure,mw,additionalMetadata,existingPatent,existingLiterature,solvent,sampleType,comments
0,0,AMR00001,AAP_1,2048,Ruby Johnson,08/10/2053,Rhodes MS,01/10/2053,16.3,NaN,...,NaN,NaN,NaN,NaN,N,N,https//doi.org/choice4,Methanol,NaN,NaN
1,1,AMR00002,MOZ42-1JR,2042,Joshua Keener,06/01/2051,Rhodes MS,30/12/2050,49.9,NaN,...,NaN,NaN,NaN,NaN,Y,N,https//doi.org/choice6,DMSO,NaN,NaN
2,2,AMR00003,TIC2041-1RH,2041,Ruby Johnson,31/01/2050,Rhodes MS/NMR,24/01/2050,94.0,NaN,...,NaN,NaN,NaN,NaN,N,N,Y,DMSO,NaN,NaN
3,3,AMR00004,MOZ42-2JR,2042,Ruby Johnson,16/10/2050,Rhodes MS/NMR,09/10/2050,95.0,NaN,...,NaN,NaN,NaN,NaN,N,N,Y,DMSO,NaN,NaN
4,4,AMR00005,TIC2041-2JR,2041,Joshua Keener,21/12/2054,"Rhodes Bioassay, PK assay",14/12/2054,14.0,NaN,...,NaN,NaN,NaN,NaN,N,N,Y,DMSO,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,AMR00096,SU-Fungi-A10,2049,Joshua Keener,27/01/2051,Rhodes MS/NMR,20/01/2051,75.5,NaN,...,NaN,NaN,NaN,NaN,Y,N,https//doi.org/choice3,Methanol,NaN,NaN
96,96,AMR00097,MOZ42-17RH,2042,Ruby Johnson,07/08/2051,Rhodes Bioassay/Rhodes MS,31/07/2051,58.7,NaN,...,NaN,NaN,NaN,NaN,Y,N,N,Methanol,NaN,NaN
97,97,AMR00098,AAP_18,2048,Joshua Keener,24/07/2053,Rhodes LC/MS + NMR & Bioassay,17/07/2053,82.8,NaN,...,NaN,NaN,NaN,NaN,Y,N,Y,Methanol,NaN,NaN
98,98,AMR00099,AMRU6A,2047,Joshua Keener,23/09/2053,Rhodes MS/NMR,16/09/2053,51.4,NaN,...,NaN,NaN,NaN,NaN,Y,N,https//doi.org/choice6,Methanol,NaN,NaN
99,99,AMR00100,AMRU7B,2045,Joshua Keener,14/01/2051,Rhodes MS,07/01/2051,72.4,NaN,...,NaN,NaN,NaN,NaN,N,N,https//doi.org/choice4,DMSO,NaN,NaN

In [1651]:
mnp_df = pd.read_excel("TrialDummy2.xlsx")
mnp_df

,mnpID,supplierID,amountAvailable,year,assignedBy,assignedDate,destinationOfSample,submittedDate,sampleType,concentration,solvent,project,sourceID,species,permitNo,researchGroup,submittedBy,level,comments
0,MNP00001,TIC2041-3RH-01,96.6,2041,Joshua Keener,10/02/2052,RU LC-MS & 1H-NMR,03/02/2052,Fraction from flash,1.00,DCM/MeOH,Marine,TIC2041-3RH,realize,RES2041,Roodt,Ruby Johnson,1,NaN
1,MNP00002,TIC2041-8RJ-01,44.1,2041,Ruby Johnson,14/12/2053,RU LC-MS & 1H-NMR,07/12/2053,SPE fraction,20.00,DCM/MeOH,Marine,TIC2041-8RJ,discuss,RES2041,Roodt,Priscilla Evans,1,NaN
2,MNP00003,TIC2041-2JR-01,0.7,2041,Ruby Johnson,18/01/2055,CD Experiment,11/01/2055,Fraction from flash,0.50,DCM/MeOH,Marine,TIC2041-2JR,though,RES2041,Smith,Priscilla Evans,1,NaN
3,MNP00004,AMRU3B-01,91.1,2045,Joshua Keener,15/01/2051,RU Bioassay,08/01/2051,SPE fraction,50.00,DCM:MeOH 2:1,Microbial,AMRU3B,day,RES2045,Smith,Priscilla Evans,1,50:50 setting
4,MNP00005,SAF43-5RH-01,93.9,2043,Ruby Johnson,29/09/2050,Rhodes MS,22/09/2050,Fraction from flash,0.10,DCM/MeOH,Marine,SAF43-5RH,attorney,RES2043,Smith,Amanda Bowker,1,20:20 setting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,MNP00256,1-1*#3R1-01aab,55.9,2046,Ruby Johnson,12/02/2055,RU Bioassay,05/02/2055,Fraction from flash,0.25,DCM:MeOH 2:1,Marine,1-1*#3R1-01aa,know,RES2046,Smith,Priscilla Evans,4,NaN
256,MNP00257,AMRU4A-01baa,72.2,2047,Ruby Johnson,23/08/2051,RU Bioassay,16/08/2051,Fraction,0.25,DCM:MeOH 2:1,Microbial,AMRU4A-01ba,myself,RES2047,Roodt,Priscilla Evans,4,NaN
257,MNP00258,AMRU1C-01aac,52.7,2045,Joshua Keener,22/01/2055,CD Experiment,15/01/2055,HPLC Fraction,0.10,DCM/MeOH,Microbial,AMRU1C-01aa,bar,RES2045,Roodt,Priscilla Evans,4,NaN
258,MNP00259,AMRU7B-02aab,70.0,2045,Joshua Keener,06/05/2051,RU Bioassay,29/04/2051,HPLC Fraction,50.00,DCM/MeOH,Microbial,AMRU7B-02aa,company,RES2045,Roodt,Ruby Johnson,4,Used compound Q in fractionation
259,MNP00260,1-1*#1R2-01aab,19.5,2046,Ruby Johnson,18/06/2050,Rhodes MS,11/06/2050,SPE fraction,0.50,DCM/MeOH,Marine,1-1*#1R2-01aa,dark,RES2046,Roodt,Amanda Bowker,4,NaN

In [1652]:
bioassay_df = pd.read_excel("bioassayDummy.xlsx")
bioassay_df

,processID,responsiblePI,researcher,dateReceived,molecularID,diluent,concentration,amount,ecoliV,ecoliSD,...,saureusBioV,saureusBioSD,pareuBioV,pareuBioSD,cytotoxV,cytotoxSD,pkActivity,dxrActivity,confirm_dxrActivity,hppkActivity
0,AMR00005,Smith,Julia Reed,21/12/2054,though,MeOH,0.50,9.9,70.4,7.1,...,95.2,7.2,16.9,8.1,24.9,1.0,100.6,82.6,4.4,108.1
1,AMR00006,Preston,Robert Hobson,26/04/2050,memory,Dried down,50.00,9.7,69.1,3.4,...,32.0,3.0,15.7,3.8,90.3,6.6,NaN,100.3,9.9,53.7
2,AMR00008,Preston,Julia Reed,09/11/2050,television,Dried down,0.10,1.3,82.1,1.0,...,39.3,3.3,30.6,5.0,6.3,7.1,7.1,71.5,43.8,101.9
3,AMR00010,Wellington,Robert Hobson,13/01/2052,realize,MeOH,1.00,5.2,46.8,7.3,...,22.9,1.3,97.9,8.0,14.7,7.2,NaN,52.8,35.6,78.7
4,AMR00011,Smith,Ruby Johnson,03/03/2050,especially,Dried down,0.50,2.3,70.6,9.9,...,36.3,1.9,25.9,5.2,33.2,3.2,NaN,44.5,22.0,37.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,MNP00233,Smith,Amanda Bowker,05/12/2050,structure,MeOH,0.10,2.3,101.0,0.6,...,15.3,3.5,74.4,9.0,89.5,7.2,NaN,69.7,23.0,59.6
132,MNP00234,Roodt,Ruby Johnson,23/08/2051,myself,MeOH,1.00,4.1,31.9,6.5,...,86.2,7.0,87.4,3.7,51.6,0.3,NaN,69.2,27.8,98.3
133,MNP00256,Smith,Priscilla Evans,12/02/2055,know,Dried down,50.00,5.0,92.4,1.0,...,28.2,7.7,73.2,2.4,85.4,2.5,NaN,31.7,0.1,31.5
134,MNP00257,Roodt,Priscilla Evans,23/08/2051,myself,MeOH,1.00,2.5,85.7,7.6,...,72.9,2.4,70.9,0.8,95.4,4.0,NaN,78.4,106.4,28.5
135,MNP00259,Roodt,Ruby Johnson,06/05/2051,company,MeOH,0.25,4.9,85.4,9.0,...,47.3,7.0,46.2,2.5,51.3,7.3,NaN,81.8,54.4,37.0

In [1653]:
collection_df = pd.read_excel('collection.xlsx')

# Separate out all collectors
collectors = collection_df['collectedBy'].unique().tolist()
separateCollectors = []
for collector in collectors:
    separateCollectors.append(collector.split(" and "))
separateCollectors = [item for sublist in separateCollectors for item in sublist]
finalCollectors = []
for collector in separateCollectors:
    finalCollectors.append(collector.split("; "))
finalCollectors = [item for sublist in finalCollectors for item in sublist]
finalCollectors = list(dict.fromkeys(finalCollectors))
finalCollectors

['Trevor Andrews', 'Clive Morrison', 'Mandy Peterson']

### person, role and person_role tables

In [1654]:
# Person_role
assigners = pd.concat([amr_df['assignedBy'], mnp_df['assignedBy']]).unique().tolist()
assignerDict = {'full_name':assigners, 'role':'Assigner'}
bioassays = bioassay_df['researcher'].unique().tolist()
bioassayDict = {'full_name':bioassays, 'role':'Bioassay Scientific Analyst'}
extractors = extract_df['submittedBy'].unique().tolist()
extractDict = {'full_name':extractors, 'role':'Extractor'}
fractionators = pd.concat([pure_df['submittedBy'], mnp_df['submittedBy']]).unique().tolist()
fractionDict = {'full_name':fractionators, 'role':'Fractionator'}
identifiers = collection_df['identifiedBy'].unique().tolist()
identifyDict = {'full_name':identifiers, 'role':'Identifier'}
collectorDict = {'full_name':finalCollectors, 'role':'Collector'}
person_role_df = pd.concat([pd.DataFrame(assignerDict), pd.DataFrame(bioassayDict), pd.DataFrame(extractDict), pd.DataFrame(fractionDict), pd.DataFrame(identifyDict), pd.DataFrame(collectorDict)], ignore_index=True)
print(assigners)
print(bioassays)
print(extractors)
print(fractionators)
print(person_role_df)

['Ruby Johnson', 'Joshua Keener']
['Julia Reed', 'Robert Hobson', 'Ruby Johnson', 'Priscilla Evans', 'Amanda Bowker']
['Julia Reed', 'Robert Hobson', 'Ruby Johnson']
['Ruby Johnson', 'Priscilla Evans', 'Amanda Bowker']
          full_name                         role
0      Ruby Johnson                     Assigner
1     Joshua Keener                     Assigner
2        Julia Reed  Bioassay Scientific Analyst
3     Robert Hobson  Bioassay Scientific Analyst
4      Ruby Johnson  Bioassay Scientific Analyst
5   Priscilla Evans  Bioassay Scientific Analyst
6     Amanda Bowker  Bioassay Scientific Analyst
7        Julia Reed                    Extractor
8     Robert Hobson                    Extractor
9      Ruby Johnson                    Extractor
10     Ruby Johnson                 Fractionator
11  Priscilla Evans                 Fractionator
12    Amanda Bowker                 Fractionator
13   Clive Morrison                   Identifier
14     Harry Warner                   Identifier
15   Trevor Andrews                    Collector
16   Clive Morrison                    Collector
17   Mandy Peterson                    Collector

In [1655]:
# Person table
collector_df = pd.DataFrame(collectorDict)
people = pd.concat([amr_df['assignedBy'], amr_df['submittedBy'], mnp_df['assignedBy'], mnp_df['submittedBy'], collection_df['identifiedBy'], collector_df['full_name']]).unique().tolist()
person_df = pd.DataFrame(people, columns=['full_name'])
person_df.insert(0, 'person_id', range(1, 1 + len(person_df)))
person_df

   person_id        full_name
0          1     Ruby Johnson
1          2    Joshua Keener
2          3       Julia Reed
3          4    Robert Hobson
4          5  Priscilla Evans
5          6    Amanda Bowker
6          7   Clive Morrison
7          8     Harry Warner
8          9   Trevor Andrews
9         10   Mandy Peterson

In [1656]:
# Role table
roles = person_role_df['role'].unique().tolist()
role_df = pd.DataFrame(roles, columns=['role'])
role_df.insert(0, 'id', range(1, 1 + len(role_df)))
role_df

   id                         role
0   1                     Assigner
1   2  Bioassay Scientific Analyst
2   3                    Extractor
3   4                 Fractionator
4   5                   Identifier
5   6                    Collector

In [1657]:
# Person role table
person_role_df.insert(2, 'person_id', 1)
person_role_df.insert(3, 'id', 1)
roleIDs = role_df['id'].tolist()
roles = role_df['role'].tolist()
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()
for rID, r in zip(roleIDs, roles):
    person_role_df.loc[person_role_df.role == r, 'id'] = rID

for pID, p in zip(personIDs, names):
    person_role_df.loc[person_role_df.full_name == p, 'person_id'] = pID

person_role_df.drop(['full_name', 'role'], axis=1, inplace=True)
person_role_df.rename(columns={'person_id':'user_id', 'id':'role_id'}, inplace=True)

person_role_df

    user_id  role_id
0         1        1
1         2        1
2         3        2
3         4        2
4         1        2
5         5        2
6         6        2
7         3        3
8         4        3
9         1        3
10        1        4
11        5        4
12        6        4
13        7        5
14        8        5
15        9        6
16        7        6
17       10        6

In [1658]:
# Person table:
# person_id, full_name, email_address, database_user, username, password
# Making email addresses based on person name
nameSeries = person_df['full_name']
emailList = []
initialList = []
passwordList = []
for index, value in nameSeries.items():
    email = ""
    initial = ""
    password = ""
    allNames = value.split(" ")
    for name in allNames:
        password = password + name[0:2].lower()
        initial = initial + name.lower()
        email = email + name[0].lower()
    email = email + "@ru.ac.za"
    password = password + "12345$"
    emailList.append(email)
    initialList.append(initial)
    passwordList.append(password)

emailSeries = pd.Series(emailList)
person_df.insert(2, 'email_address', emailSeries)
userSeries = pd.Series(initialList)
passwordSeries = pd.Series(passwordList)

# Saying only those who are assigners have current access to database
# Only those will have usernames and passwords
person_df.insert(3, 'database_user', "N")
person_df.loc[person_role_df['role_id'] == 1, 'database_user'] = "Y"
person_df.insert(4, 'username', userSeries)
person_df.loc[person_df['database_user'] == "N", 'username'] = None
person_df.insert(5, 'password', passwordSeries)
person_df.loc[person_df['database_user'] == "N", 'password'] = None
person_df

,person_id,full_name,email_address,database_user,username,password
0,1,Ruby Johnson,rj@ru.ac.za,Y,rubyjohnson,rujo12345$
1,2,Joshua Keener,jk@ru.ac.za,Y,joshuakeener,joke12345$
2,3,Julia Reed,jr@ru.ac.za,N,None,None
3,4,Robert Hobson,rh@ru.ac.za,N,None,None
4,5,Priscilla Evans,pe@ru.ac.za,N,None,None
5,6,Amanda Bowker,ab@ru.ac.za,N,None,None
6,7,Clive Morrison,cm@ru.ac.za,N,None,None
7,8,Harry Warner,hw@ru.ac.za,N,None,None
8,9,Trevor Andrews,ta@ru.ac.za,N,None,None
9,10,Mandy Peterson,mp@ru.ac.za,N,None,None

### Research Group table

In [1659]:
# Research group that the samples belong to
group = pd.concat([amr_df['researchGroup'], mnp_df['researchGroup'], bioassay_df['responsiblePI']]).unique().tolist()
group_df = pd.DataFrame(group, columns=['group_name'])
group_df.insert(0, 'group_id',  range(1, 1 + len(group_df)))
group_df

   group_id  group_name
0         1       Roodt
1         2       Smith
2         3  Wellington
3         4     Preston
4         5      Howard
5         6        Leer
6         7    Ackerman

### Extract table

In [1660]:
# Need supplierID, submittedDate, amountAvailable, ms, nmr, researchGroup, submittedBy (as submitterID), existingLiterature, sourceID, sourceType, solvent
extract = extract_df[["supplierID", "submittedDate", "amountAvailable", "ms", "nmr", "researchGroup", "submittedBy", "existingLiterature", "sourceID", "sourceType", "solvent"]]
extract.rename(columns={'supplierID':'extract_id', 'submittedDate':'date_sample_submitted', 'amountAvailable':'amount_available', 'researchGroup':'research_group', 'sourceID':'source_id', 'sourceType':'source_type', 'solvent':'solvent_extraction'}, inplace=True)

# Turn submittedBy to submitterID
extract.insert(6, 'submitter_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    extract.loc[extract.submittedBy == p, 'submitter_id'] = pID


# Make existing Literature into two columns - Y or N, and any hyperlinks in second
extract.insert(9, 'existing_literature', 'Y')
extract.insert(10, 'literature_link', extract['existingLiterature'])
extract.loc[extract['existingLiterature'] == 'N', 'existing_literature'] = 'N'

# Replace research_group with research_group_id
extract.insert(6, 'researchgroup_id', 1)
groupIDs = group_df['group_id'].tolist()
groupnames = group_df['group_name'].tolist()

for gID, g in zip(groupIDs, groupnames):
    extract.loc[extract.research_group == g, 'researchgroup_id'] = gID

extract.drop(['submittedBy'], axis=1, inplace=True)
extract.drop(['existingLiterature'], axis=1, inplace=True)
extract.drop(['research_group'], axis=1, inplace=True)
# Convert Y and N to True and False
extract = extract.replace({'ms':{'Y':True, 'N':False}, 'nmr':{'Y':True, 'N':False}, 'existing_literature':{'Y':True, 'N':False}, 'literature_link':{'Y':None, 'N':None}})
# Convert date_submitted from string to date type
extract['date_sample_submitted'] = pd.to_datetime(extract['date_sample_submitted'])
extract

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2916505010.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extract.rename(columns={'supplierID':'extract_id', 'submittedDate':'date_sample_submitted', 'amountAvailable':'amount_available', 'researchGroup':'research_group', 'sourceID':'source_id', 'sourceType':'source_type', 'solvent':'solvent_extraction'}, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2916505010.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extract.drop(['submittedBy'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2916505010.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extract.drop(['existingLiterature'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2916505010.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extract.drop(['research_group'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2916505010.py:33: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  extract['date_sample_submitted'] = pd.to_datetime(extract['date_sample_submitted'])

,extract_id,date_sample_submitted,amount_available,ms,nmr,researchgroup_id,submitter_id,existing_literature,literature_link,source_id,source_type,solvent_extraction
0,AAP_1,2053-01-10,16.3,False,True,1,3,True,https//doi.org/choice4,AAP_1,Bacterial,Methanol
1,MOZ42-1JR,2050-12-30,49.9,True,False,2,3,True,https//doi.org/choice6,MOZ42-1,MNP,DMSO
2,TIC2041-1RH,2050-01-24,94.0,False,True,3,4,True,None,TIC2041-1,MNP,DMSO
3,MOZ42-2JR,2050-09-10,95.0,True,False,4,3,True,None,MOZ42-2,MNP,DMSO
4,TIC2041-2JR,2054-12-14,14.0,True,False,2,3,True,None,TIC2041-2,MNP,DMSO
...,...,...,...,...,...,...,...,...,...,...,...,...
95,SU-Fungi-A10,2051-01-20,75.5,True,False,1,4,True,https//doi.org/choice3,SU-Fungi-A10,Soil,Methanol
96,MOZ42-17RH,2051-07-31,58.7,True,True,4,4,False,None,MOZ42-17,MNP,Methanol
97,AAP_18,2053-07-17,82.8,False,False,4,4,True,None,AAP_18,Bacterial,Methanol
98,AMRU6A,2053-09-16,51.4,False,False,1,4,True,https//doi.org/choice6,OB4-REP1_3,Stromatolites,Methanol
99,AMRU7B,2051-07-01,72.4,True,True,4,3,True,https//doi.org/choice4,CSF_1ABC_4,Stromatolites,DMSO

### Fraction table

In [1661]:
# Need supplierID, submittedDate, amountAvailable, sampleType, concentration, project, sourceID, researchGroup, submittedBy, solvent, level, comments
fraction = mnp_df[["supplierID", "submittedDate", "amountAvailable", "sampleType", "concentration", "project", "sourceID", "researchGroup", "submittedBy", "solvent", "level", "comments"]]
fraction.rename(columns={'supplierID':'fraction_id', 'submittedDate':'date_sample_submitted', 'amountAvailable':'amount_available', 'sampleType':'sample_type', 'researchGroup':'research_group', 'sourceID':'source_id', 'solvent':'solvent_used'}, inplace=True)

# Turn submittedBy to submitterID
fraction.insert(8, 'submitter_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    fraction.loc[fraction.submittedBy == p, 'submitter_id'] = pID

# Replace research_group with research_group_id
fraction.insert(8, 'researchgroup_id', 1)
groupIDs = group_df['group_id'].tolist()
groupnames = group_df['group_name'].tolist()

for gID, g in zip(groupIDs, groupnames):
    fraction.loc[fraction.research_group == g, 'researchgroup_id'] = gID

fraction.drop(['submittedBy'], axis=1, inplace=True)
fraction.drop(['research_group'], axis=1, inplace=True)
fraction['date_sample_submitted'] = pd.to_datetime(fraction['date_sample_submitted'])
fraction

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\218957866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraction.rename(columns={'supplierID':'fraction_id', 'submittedDate':'date_sample_submitted', 'amountAvailable':'amount_available', 'sampleType':'sample_type', 'researchGroup':'research_group', 'sourceID':'source_id', 'solvent':'solvent_used'}, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\218957866.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraction.drop(['submittedBy'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\218957866.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraction.drop(['research_group'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\218957866.py:23: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  fraction['date_sample_submitted'] = pd.to_datetime(fraction['date_sample_submitted'])
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\218957866.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fraction['date_sample_submitted'] = pd.to_datetime(fraction['date_sample_submitted'])

,fraction_id,date_sample_submitted,amount_available,sample_type,concentration,project,source_id,researchgroup_id,submitter_id,solvent_used,level,comments
0,TIC2041-3RH-01,2052-03-02,96.6,Fraction from flash,1.00,Marine,TIC2041-3RH,1,1,DCM/MeOH,1,NaN
1,TIC2041-8RJ-01,2053-07-12,44.1,SPE fraction,20.00,Marine,TIC2041-8RJ,1,5,DCM/MeOH,1,NaN
2,TIC2041-2JR-01,2055-11-01,0.7,Fraction from flash,0.50,Marine,TIC2041-2JR,2,5,DCM/MeOH,1,NaN
3,AMRU3B-01,2051-08-01,91.1,SPE fraction,50.00,Microbial,AMRU3B,2,5,DCM:MeOH 2:1,1,50:50 setting
4,SAF43-5RH-01,2050-09-22,93.9,Fraction from flash,0.10,Marine,SAF43-5RH,2,6,DCM/MeOH,1,20:20 setting
...,...,...,...,...,...,...,...,...,...,...,...,...
255,1-1*#3R1-01aab,2055-05-02,55.9,Fraction from flash,0.25,Marine,1-1*#3R1-01aa,2,5,DCM:MeOH 2:1,4,NaN
256,AMRU4A-01baa,2051-08-16,72.2,Fraction,0.25,Microbial,AMRU4A-01ba,1,5,DCM:MeOH 2:1,4,NaN
257,AMRU1C-01aac,2055-01-15,52.7,HPLC Fraction,0.10,Microbial,AMRU1C-01aa,1,5,DCM/MeOH,4,NaN
258,AMRU7B-02aab,2051-04-29,70.0,HPLC Fraction,50.00,Microbial,AMRU7B-02aa,1,1,DCM/MeOH,4,Used compound Q in fractionation
259,1-1*#1R2-01aab,2050-11-06,19.5,SPE fraction,0.50,Marine,1-1*#1R2-01aa,1,6,DCM/MeOH,4,NaN

### Derivedpurecomp table

In [1662]:
# Need: supplierID, submittedDate, amountAvailable, synthesisPotential, sourceID, ms, nmr, submittedBy, solubility, stereoComments, smileStructure, mw, additionalMetadata, existingPatent, existingLiterature, solvent
# Decide if need fractionMethod
derivedpurecomp = pure_df[["supplierID", "submittedDate", "amountAvailable", "synthesisPotential", "sourceID", "ms", "nmr", "researchGroup", "submittedBy", "solubility", "stereoComments", "smileStructure", "mw", "additionalMetadata", "existingPatent", "existingLiterature", "solvent", "sampleType", "comments"]]
derivedpurecomp.rename(columns={'supplierID':'derivedpurecomp_id', 'submittedDate':'date_sample_submitted', 'amountAvailable':'amount_available', 'synthesisPotential':'synthesis_potential', 'existingPatent':'existing_patent', 'sourceID':'source_id', 'sourceType':'source_type', 'solvent':'solvent_used', 'stereoComments':'stereo_comments', 'smileStructure':'smile_structure', 'additionalMetadata':'additional_metadata', 'sampleType':'fraction_method'}, inplace=True)
# Turn submittedBy to submitterID
derivedpurecomp.insert(8, 'submitter_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    derivedpurecomp.loc[derivedpurecomp.submittedBy == p, 'submitter_id'] = pID

# Replace research_group with research_group_id
derivedpurecomp.insert(8, 'researchgroup_id', 1)
groupIDs = group_df['group_id'].tolist()
groupnames = group_df['group_name'].tolist()

for gID, g in zip(groupIDs, groupnames):
    derivedpurecomp.loc[derivedpurecomp.researchGroup == g, 'researchgroup_id'] = gID

# Make existing Literature into two columns - Y or N, and any hyperlinks in second
derivedpurecomp.insert(18, 'existing_literature', 'Y')
derivedpurecomp.insert(19, 'literature_link', derivedpurecomp['existingLiterature'])
derivedpurecomp.loc[derivedpurecomp['existingLiterature'] == 'N', 'existing_literature'] = 'N'

derivedpurecomp.drop(['submittedBy'], axis=1, inplace=True)
derivedpurecomp.drop(['researchGroup'], axis=1, inplace=True)
derivedpurecomp.drop(['existingLiterature'], axis=1, inplace=True)
# Turn yes and no into boolean for table (True or False)
derivedpurecomp = derivedpurecomp.replace({'ms':{'Y':True, 'N':False}, 'nmr':{'Y':True, 'N':False}, 'existing_literature':{'Y':True, 'N':False}, 'literature_link':{'Y':None, 'N':None}, 'existing_patent':{'Y':True, 'N':False}, 'additional_metadata':{'Y':True, 'N':False}, 'existing_literature':{'Y':True, 'N':False}, 'synthesis_potential':{'Y':True, 'N':False}})
# Date must be converted to datetime format for the database
derivedpurecomp['date_sample_submitted'] = pd.to_datetime(derivedpurecomp['date_sample_submitted'])

derivedpurecomp.head()

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2042327622.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  derivedpurecomp.rename(columns={'supplierID':'derivedpurecomp_id', 'submittedDate':'date_sample_submitted', 'amountAvailable':'amount_available', 'synthesisPotential':'synthesis_potential', 'existingPatent':'existing_patent', 'sourceID':'source_id', 'sourceType':'source_type', 'solvent':'solvent_used', 'stereoComments':'stereo_comments', 'smileStructure':'smile_structure', 'additionalMetadata':'additional_metadata', 'sampleType':'fraction_method'}, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2042327622.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  derivedpurecomp.drop(['submittedBy'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2042327622.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  derivedpurecomp.drop(['researchGroup'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2042327622.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  derivedpurecomp.drop(['existingLiterature'], axis=1, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2042327622.py:32: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  derivedpurecomp['date_sample_submitted'] = pd.to_datetime(derivedpurecomp['date_sample_submitted'])

,derivedpurecomp_id,date_sample_submitted,amount_available,synthesis_potential,source_id,ms,nmr,researchgroup_id,submitter_id,solubility,stereo_comments,smile_structure,mw,additional_metadata,existing_patent,existing_literature,literature_link,solvent_used,fraction_method,comments
0,PC-MOZ42-13RH-02ba,2055-03-25,88.2,False,MOZ42-13RH-02b,True,False,5,1,DMSO,InterestPC5,former,126.2,False,True,True,https://doi.org/comp3,MeOH,SPE fraction,Used compound G in fractionation
1,PC-1-1*#2R2-02aa,2052-01-23,29.4,True,1-1*#2R2-02a,True,True,2,5,"aq.MeOH, MeOH",InterestPC10,fish,280.6,True,True,True,None,MeOH,Fraction from flash,70:30 setting
2,PC-AMRU5B-01ba,2051-09-27,13.6,True,AMRU5B-01b,False,True,6,1,DCM: MeOH 2:1,InterestPC1,Mr,115.1,True,True,True,https://doi.org/comp4,DCM/MeOH,SPE fraction,NaN
3,PC-MOZ42-1JR-01ab,2051-03-24,67.3,False,MOZ42-1JR-01a,False,True,7,1,DMSO,InterestPC8,five,26.9,False,True,True,https://doi.org/comp3,DCM:MeOH 2:1,SPE fraction,NaN
4,PC-MOZ42-3RH-02aa,2050-12-07,39.7,False,MOZ42-3RH-02a,False,False,6,1,"aq.MeOH, MeOH",InterestPC10,crime,215.5,False,True,True,https://doi.org/comp6,DCM:MeOH 2:1,Fraction from flash,NaN

### Process table

In [1663]:
# Need from extract_df, fraction and pure_df
# processID (AMRID or MNPID), supplierID, assignedBy, assignedDate, destination, sample_level (extract, fraction, pure comp)
processExtract = extract_df[["amrID", "supplierID", "assignedBy", "assignedDate", "destinationOfSample"]]
processExtract.insert(5, 'sample_level', "Extract")
processExtract.rename(columns={'amrID':'process_id'}, inplace=True)
processFraction = mnp_df[["mnpID", "supplierID", "assignedBy", "assignedDate", "destinationOfSample"]]
processFraction.insert(5, 'sample_level', "Fraction")
processFraction.rename(columns={'mnpID':'process_id'}, inplace=True)
processPure = pure_df[["amrID", "supplierID", "assignedBy", "assignedDate", "destinationOfSample"]]
processPure.insert(5, 'sample_level', "PureCompound")
processPure.rename(columns={'amrID':'process_id'}, inplace=True)
process = pd.concat([processExtract, processFraction, processPure], ignore_index=True)
process.rename(columns={'supplierID':'supplier_id', 'assignedDate':'date_assigned', 'destinationOfSample':'destination_of_sample'}, inplace=True)
process.insert(2, 'assigner_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    process.loc[process.assignedBy == p, 'assigner_id'] = pID

process.drop(['assignedBy'], axis=1, inplace=True)
# Date must be converted to datetime format for the database
process['date_assigned'] = pd.to_datetime(process['date_assigned'])
process

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\299531478.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processExtract.rename(columns={'amrID':'process_id'}, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\299531478.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processFraction.rename(columns={'mnpID':'process_id'}, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\299531478.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processPure.rename(columns={'amrID':'process_id'}, inplace=True)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\299531478.py:23: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  process['date_assigned'] = pd.to_datetime(process['date_assigned'])

,process_id,supplier_id,assigner_id,date_assigned,destination_of_sample,sample_level
0,AMR00001,AAP_1,1,2053-08-10,Rhodes MS,Extract
1,AMR00002,MOZ42-1JR,2,2051-06-01,Rhodes MS,Extract
2,AMR00003,TIC2041-1RH,1,2050-01-31,Rhodes MS/NMR,Extract
3,AMR00004,MOZ42-2JR,1,2050-10-16,Rhodes MS/NMR,Extract
4,AMR00005,TIC2041-2JR,2,2054-12-21,"Rhodes Bioassay, PK assay",Extract
...,...,...,...,...,...,...
415,AMR00156,PC-AMRU3B-02bbd,1,2051-09-04,Rhodes LC/MS + NMR & Bioassay,PureCompound
416,AMR00157,PC-AMRU7B-02aaa,2,2051-06-05,Membrane Disruption assay,PureCompound
417,AMR00158,PC-AMRU3B-02bba,1,2051-09-04,"Rhodes Bioassay, PK assay",PureCompound
418,AMR00159,PC-MOZ42-13RH-01aba,2,2055-04-29,Rhodes MS,PureCompound
419,AMR00160,PC-1-1*#1R3-01caa,1,2052-11-24,Rhodes MS,PureCompound

### Mass spec raw table

In [1664]:
# Find where destination of sample is MS, but not LC/MS or LC-MS
ms_records = process[process.destination_of_sample.str.contains('MS', regex=False)]
ms_records = ms_records.drop(ms_records[ms_records.destination_of_sample.str.contains('LC/MS', regex=False)].index)
ms_records = ms_records.drop(ms_records[ms_records.destination_of_sample.str.contains('LC-MS', regex=False)].index)
ms_records.drop(['supplier_id', 'assigner_id', 'destination_of_sample', 'sample_level'], axis=1, inplace=True)

# Now make mass spec records for each of these
# massspec_id will be autocreated (incrementing by 1), process_id, date_requested will be same as date_assigned, cancelled all false, date_submitted will all be None, link_processed_spec all None
ms_records.insert(2, 'cancelled', False)
# ms_records.insert(3, 'link_processed_spec', None)
# ms_records.insert(4, 'date_submitted', None)
ms_records.rename(columns={'date_assigned':'date_requested'}, inplace=True)
# Date must be converted to datetime format for the database
ms_records['date_requested'] = pd.to_datetime(ms_records['date_requested'])
ms_records

    process_id date_requested  cancelled
0     AMR00001     2053-08-10      False
1     AMR00002     2051-06-01      False
2     AMR00003     2050-01-31      False
3     AMR00004     2050-10-16      False
18    AMR00019     2051-07-30      False
..         ...            ...        ...
409   AMR00150     2054-09-29      False
412   AMR00153     2054-08-03      False
414   AMR00155     2054-01-24      False
418   AMR00159     2055-04-29      False
419   AMR00160     2052-11-24      False

[115 rows x 3 columns]

In [1665]:
# Get 80% of these records and make mass spec info as if they were already uploaded
massProcessed = ms_records.sample(frac=0.8).reset_index(drop=True)

#Then create fake link
fake = Faker()
Faker.seed(1234)
random.seed(1234)

class Provider(BaseProvider):
    def link_processed_spec(self):
        return "/ms/" + fake.word()

# Add the Provider to our faker object
fake.add_provider(Provider)

# Go up by one for AMR ID
# Supplier ID - based on date of collection, so must be same or earlier year than submittedDate
#               some TIC, some SAF, Some strains (e.g. S 20 20), MIAP_155, HMF-1, MBA_F406_PDM
# Date assigned - do a week after submittedDate
# Source ID - TIC number, MIAP etc - based on Supplier ID (start with this, then make Supplier ID)
# Source type - based on source ID (microbial vs sponge vs stromatolite)
# Permit - RES and year before or same as source ID

def create_ms_data(fake, no_of_rows):
    columns = ['link_processed_spec']
    data =  {column: [getattr(fake, column)() for _ in range(no_of_rows)] for column in columns}
    df = pd.DataFrame(data=data)
    df = df[columns]

    return df

original_df = create_ms_data(fake, len(massProcessed))
totalms = pd.concat([massProcessed, original_df], axis=1)
# Make date submitted 2 weeks after date requested
totalms.insert(4, 'date_submitted', totalms['date_requested'])
# Date submitted - do 3 weeks after previous assignedDate
totalms['date_submitted'] = totalms['date_submitted'] + timedelta(days=14)

newms = ms_records.merge(totalms, on=['process_id', 'date_requested', 'cancelled'], how='left')
newms

    process_id date_requested  cancelled link_processed_spec date_submitted
0     AMR00001     2053-08-10      False            /ms/most     2053-08-24
1     AMR00002     2051-06-01      False            /ms/ball     2051-06-15
2     AMR00003     2050-01-31      False            /ms/goal     2050-02-14
3     AMR00004     2050-10-16      False           /ms/enjoy     2050-10-30
4     AMR00019     2051-07-30      False                 NaN            NaT
..         ...            ...        ...                 ...            ...
110   AMR00150     2054-09-29      False            /ms/only     2054-10-13
111   AMR00153     2054-08-03      False             /ms/man     2054-08-17
112   AMR00155     2054-01-24      False          /ms/really     2054-02-07
113   AMR00159     2055-04-29      False           /ms/movie     2055-05-13
114   AMR00160     2052-11-24      False           /ms/write     2052-12-08

[115 rows x 5 columns]

### NMR table

In [1666]:
# Find where destination of sample is NMR
nmr = process[process.destination_of_sample.str.contains('NMR', regex=False)]
nmr_records = nmr.drop(['supplier_id', 'assigner_id', 'destination_of_sample', 'sample_level'], axis=1)

# Now make mass spec records for each of these
# massspec_id will be autocreated (incrementing by 1), process_id, date_requested will be same as date_assigned, cancelled all false, date_submitted will all be None, link_processed_spec all None
nmr_records.insert(2, 'cancelled', False)
# nmr_records.insert(3, 'link_folder', None)
# nmr_records.insert(4, 'date_submitted', None)
nmr_records.rename(columns={'date_assigned':'date_requested'}, inplace=True)
# Date must be converted to datetime format for the database
nmr_records['date_requested'] = pd.to_datetime(nmr_records['date_requested'])
nmr_records

    process_id date_requested  cancelled
2     AMR00003     2050-01-31      False
3     AMR00004     2050-10-16      False
5     AMR00006     2050-04-26      False
10    AMR00011     2050-03-03      False
11    AMR00012     2050-04-13      False
..         ...            ...        ...
396   AMR00137     2054-12-04      False
401   AMR00142     2054-08-05      False
407   AMR00148     2051-04-28      False
413   AMR00154     2054-09-16      False
415   AMR00156     2051-09-04      False

[116 rows x 3 columns]

In [1667]:
# Get 80% of these records and make mass spec info as if they were already uploaded
nmrProcessed = nmr_records.sample(frac=0.8).reset_index(drop=True)

#Then create fake link
fake = Faker()
Faker.seed(1234)
random.seed(1234)

class Provider(BaseProvider):
    def link_folder(self):
        return "/nmr/" + fake.word()

# Add the Provider to our faker object
fake.add_provider(Provider)

# Go up by one for AMR ID
# Supplier ID - based on date of collection, so must be same or earlier year than submittedDate
#               some TIC, some SAF, Some strains (e.g. S 20 20), MIAP_155, HMF-1, MBA_F406_PDM
# Date assigned - do a week after submittedDate
# Source ID - TIC number, MIAP etc - based on Supplier ID (start with this, then make Supplier ID)
# Source type - based on source ID (microbial vs sponge vs stromatolite)
# Permit - RES and year before or same as source ID

def create_nmr_data(fake, no_of_rows):
    columns = ['link_folder']
    data =  {column: [getattr(fake, column)() for _ in range(no_of_rows)] for column in columns}
    df = pd.DataFrame(data=data)
    df = df[columns]

    return df

original_df = create_nmr_data(fake, len(massProcessed))
totalnmr = pd.concat([nmrProcessed, original_df], axis=1)
# Make date submitted 2 weeks after date requested
totalnmr.insert(4, 'date_submitted', totalnmr['date_requested'])
# Date submitted - do 3 weeks after previous assignedDate
totalnmr['date_submitted'] = totalnmr['date_submitted'] + timedelta(days=14)

newnmr = nmr_records.merge(totalnmr, on=['process_id', 'date_requested', 'cancelled'], how='left')
newnmr

    process_id date_requested  cancelled     link_folder date_submitted
0     AMR00003     2050-01-31      False      /nmr/thank     2050-02-14
1     AMR00004     2050-10-16      False         /nmr/to     2050-10-30
2     AMR00006     2050-04-26      False      /nmr/allow     2050-05-10
3     AMR00011     2050-03-03      False       /nmr/onto     2050-03-17
4     AMR00012     2050-04-13      False      /nmr/admit     2050-04-27
..         ...            ...        ...             ...            ...
111   AMR00137     2054-12-04      False     /nmr/worker     2054-12-18
112   AMR00142     2054-08-05      False  /nmr/agreement     2054-08-19
113   AMR00148     2051-04-28      False      /nmr/story     2051-05-12
114   AMR00154     2054-09-16      False             NaN            NaT
115   AMR00156     2051-09-04      False       /nmr/room     2051-09-18

[116 rows x 5 columns]

### LC-MS table

In [1668]:
lcms = process[process.destination_of_sample.str.contains("LC-MS", regex=False)].append(process[process.destination_of_sample.str.contains("LC/MS", regex=False)])
lcms_records = lcms.drop(['supplier_id', 'assigner_id', 'destination_of_sample', 'sample_level'], axis=1)

# Now make mass spec records for each of these
# massspec_id will be autocreated (incrementing by 1), process_id, date_requested will be same as date_assigned, cancelled all false, date_submitted will all be None, link_processed_spec all None
lcms_records.insert(2, 'cancelled', False)
lcms_records.rename(columns={'date_assigned':'date_requested'}, inplace=True)
# Date must be converted to datetime format for the database
lcms_records['date_requested'] = pd.to_datetime(lcms_records['date_requested'])
lcms_records

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\656750662.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  lcms = process[process.destination_of_sample.str.contains("LC-MS", regex=False)].append(process[process.destination_of_sample.str.contains("LC/MS", regex=False)])

    process_id date_requested  cancelled
100   MNP00001     2052-10-02      False
101   MNP00002     2053-12-14      False
105   MNP00006     2050-05-24      False
120   MNP00021     2050-03-31      False
121   MNP00022     2053-01-11      False
..         ...            ...        ...
376   AMR00117     2052-01-30      False
396   AMR00137     2054-12-04      False
401   AMR00142     2054-08-05      False
413   AMR00154     2054-09-16      False
415   AMR00156     2051-09-04      False

[132 rows x 3 columns]

In [1669]:
proc_df = process[['process_id', 'destination_of_sample']]
df_all = proc_df[proc_df.destination_of_sample.str.contains("Bioassay", regex=False)].append(proc_df[proc_df.destination_of_sample.str.contains("PK", regex=False)])
# Get only pk
pks = proc_df[proc_df.destination_of_sample.str.contains("PK", regex=False)]
# Find values where indexes are same, and put True in pk_requested
pkProcess = df_all.merge(pks.drop_duplicates(), on=['process_id', "destination_of_sample"], how='left', indicator=True)
pkProcess['_merge'] = (pkProcess['_merge'] == 'both')
pkProcess.rename(columns={'_merge':'pk_requested'}, inplace=True)
bioassay_df.insert(24, 'pk_requested', True)
bioassay_df.loc[bioassay_df['pkActivity'].isnull(), 'pk_requested'] = False
bioassay_df.rename(columns={'processID':'process_id', 'dateReceived':'date_received', 'molecularID':'molecular_id', 'ecoliV':'ecoli_v', 'ecoliSD':'ecoli_sd', 'saureusV':'saureus_v', 'saureusSD':'saureus_sd', 'pareuV':'pareu_v', 'pareuSD':'pareu_sd', 'saureusBioV':'saureus_bio_v', 'saureusBioSD':'saureus_bio_sd',
                'pareuBioV':'pareu_bio_v', 'pareuBioSD':'pareu_bio_sd', 'cytotoxV':'cytotox_v', 'cytotoxSD':'cytotox_sd', 'pkActivity':'pk_activity', 'dxrActivity':'dxr_activity', 'confirm_dxrActivity':'confirm_dxr_activity', 'hppkActivity':'hppk_activity'}, inplace=True)
bioassay_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2607523635.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = proc_df[proc_df.destination_of_sample.str.contains("Bioassay", regex=False)].append(proc_df[proc_df.destination_of_sample.str.contains("PK", regex=False)])

,process_id,responsiblePI,researcher,date_received,molecular_id,diluent,concentration,amount,ecoli_v,ecoli_sd,...,saureus_bio_sd,pareu_bio_v,pareu_bio_sd,cytotox_v,cytotox_sd,pk_activity,dxr_activity,confirm_dxr_activity,hppk_activity,pk_requested
0,AMR00005,Smith,Julia Reed,21/12/2054,though,MeOH,0.50,9.9,70.4,7.1,...,7.2,16.9,8.1,24.9,1.0,100.6,82.6,4.4,108.1,True
1,AMR00006,Preston,Robert Hobson,26/04/2050,memory,Dried down,50.00,9.7,69.1,3.4,...,3.0,15.7,3.8,90.3,6.6,NaN,100.3,9.9,53.7,False
2,AMR00008,Preston,Julia Reed,09/11/2050,television,Dried down,0.10,1.3,82.1,1.0,...,3.3,30.6,5.0,6.3,7.1,7.1,71.5,43.8,101.9,True
3,AMR00010,Wellington,Robert Hobson,13/01/2052,realize,MeOH,1.00,5.2,46.8,7.3,...,1.3,97.9,8.0,14.7,7.2,NaN,52.8,35.6,78.7,False
4,AMR00011,Smith,Ruby Johnson,03/03/2050,especially,Dried down,0.50,2.3,70.6,9.9,...,1.9,25.9,5.2,33.2,3.2,NaN,44.5,22.0,37.8,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,MNP00233,Smith,Amanda Bowker,05/12/2050,structure,MeOH,0.10,2.3,101.0,0.6,...,3.5,74.4,9.0,89.5,7.2,NaN,69.7,23.0,59.6,False
132,MNP00234,Roodt,Ruby Johnson,23/08/2051,myself,MeOH,1.00,4.1,31.9,6.5,...,7.0,87.4,3.7,51.6,0.3,NaN,69.2,27.8,98.3,False
133,MNP00256,Smith,Priscilla Evans,12/02/2055,know,Dried down,50.00,5.0,92.4,1.0,...,7.7,73.2,2.4,85.4,2.5,NaN,31.7,0.1,31.5,False
134,MNP00257,Roodt,Priscilla Evans,23/08/2051,myself,MeOH,1.00,2.5,85.7,7.6,...,2.4,70.9,0.8,95.4,4.0,NaN,78.4,106.4,28.5,False
135,MNP00259,Roodt,Ruby Johnson,06/05/2051,company,MeOH,0.25,4.9,85.4,9.0,...,7.0,46.2,2.5,51.3,7.3,NaN,81.8,54.4,37.0,False

In [1670]:
# Replace research_group with research_group_id
bioassay_df.insert(2, 'responsible_pi_id', 1)
groupIDs = group_df['group_id'].tolist()
groupnames = group_df['group_name'].tolist()

for gID, g in zip(groupIDs, groupnames):
    bioassay_df.loc[bioassay_df.responsiblePI == g, 'responsible_pi_id'] = gID

# Turn submittedBy to submitterID
bioassay_df.insert(4, 'researcher_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    bioassay_df.loc[bioassay_df.researcher == p, 'researcher_id'] = pID

bioassay_df.drop(['responsiblePI', 'researcher'], axis=1, inplace=True)
# Date must be converted to datetime format for the database
bioassay_df['date_received'] = pd.to_datetime(bioassay_df['date_received'])

bioassay_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\3263007454.py:19: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  bioassay_df['date_received'] = pd.to_datetime(bioassay_df['date_received'])

,process_id,responsible_pi_id,researcher_id,date_received,molecular_id,diluent,concentration,amount,ecoli_v,ecoli_sd,...,saureus_bio_sd,pareu_bio_v,pareu_bio_sd,cytotox_v,cytotox_sd,pk_activity,dxr_activity,confirm_dxr_activity,hppk_activity,pk_requested
0,AMR00005,2,3,2054-12-21,though,MeOH,0.50,9.9,70.4,7.1,...,7.2,16.9,8.1,24.9,1.0,100.6,82.6,4.4,108.1,True
1,AMR00006,4,4,2050-04-26,memory,Dried down,50.00,9.7,69.1,3.4,...,3.0,15.7,3.8,90.3,6.6,NaN,100.3,9.9,53.7,False
2,AMR00008,4,3,2050-09-11,television,Dried down,0.10,1.3,82.1,1.0,...,3.3,30.6,5.0,6.3,7.1,7.1,71.5,43.8,101.9,True
3,AMR00010,3,4,2052-01-13,realize,MeOH,1.00,5.2,46.8,7.3,...,1.3,97.9,8.0,14.7,7.2,NaN,52.8,35.6,78.7,False
4,AMR00011,2,1,2050-03-03,especially,Dried down,0.50,2.3,70.6,9.9,...,1.9,25.9,5.2,33.2,3.2,NaN,44.5,22.0,37.8,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,MNP00233,2,6,2050-05-12,structure,MeOH,0.10,2.3,101.0,0.6,...,3.5,74.4,9.0,89.5,7.2,NaN,69.7,23.0,59.6,False
132,MNP00234,1,1,2051-08-23,myself,MeOH,1.00,4.1,31.9,6.5,...,7.0,87.4,3.7,51.6,0.3,NaN,69.2,27.8,98.3,False
133,MNP00256,2,5,2055-12-02,know,Dried down,50.00,5.0,92.4,1.0,...,7.7,73.2,2.4,85.4,2.5,NaN,31.7,0.1,31.5,False
134,MNP00257,1,5,2051-08-23,myself,MeOH,1.00,2.5,85.7,7.6,...,2.4,70.9,0.8,95.4,4.0,NaN,78.4,106.4,28.5,False
135,MNP00259,1,1,2051-06-05,company,MeOH,0.25,4.9,85.4,9.0,...,7.0,46.2,2.5,51.3,7.3,NaN,81.8,54.4,37.0,False

### HPLC Table

### Countries Table

In [1671]:
countries_df = pd.read_csv('data_csv.txt')
countries_df.rename(columns={'Name':'country_name', 'Code':'country_id'}, inplace=True)
countries_df

          country_name country_id
0          Afghanistan         AF
1        Åland Islands         AX
2              Albania         AL
3              Algeria         DZ
4       American Samoa         AS
..                 ...        ...
244  Wallis and Futuna         WF
245     Western Sahara         EH
246              Yemen         YE
247             Zambia         ZM
248           Zimbabwe         ZW

[249 rows x 2 columns]

### Regions Table

In [1672]:
regions_df = pd.read_excel('regions.xlsx')
regions_df.rename(columns={'Region ID':'region_id', 'Region Name':'region_name', 'Country ID':'country_id'}, inplace=True)
regions_df

   region_id          region_name country_id
0       MZ-P         Cabo Delgado         MZ
1       MZ-G                 Gaza         MZ
2       MZ-I            Inhambane         MZ
3       MZ-B               Manica         MZ
4       MZ-L               Maputo         MZ
5       MZ-N              Nampula         MZ
6       MZ-A               Niassa         MZ
7       MZ-S               Sofala         MZ
8       MZ-T                 Tete         MZ
9       MZ-Q             Zambézia         MZ
10     ZA-EC         Eastern Cape         ZA
11     ZA-FS           Free State         ZA
12       NaN                  NaN         ZA
13     ZA-GP              Gauteng         ZA
14    ZA-KZN        Kwazulu-Natal         ZA
15     ZA-LP              Limpopo         ZA
16     ZA-MP           Mpumalanga         ZA
17     ZA-NW           North-West         ZA
18     ZA-NC        Northern Cape         ZA
19     ZA-WC         Western Cape         ZA
20     SC-01        Anse aux Pins         SC
21     SC-02         Anse Boileau         SC
22     SC-03          Anse Etoile         SC
23     SC-05          Anse Royale         SC
24     SC-04               Au Cap         SC
25     SC-06          Baie Lazare         SC
26     SC-07     Baie Sainte Anne         SC
27     SC-08          Beau Vallon         SC
28     SC-09              Bel Air         SC
29     SC-10            Bel Ombre         SC
30     SC-11              Cascade         SC
31     SC-16        English River         SC
32     SC-12               Glacis         SC
33     SC-13      Grand Anse Mahe         SC
34     SC-14   Grand Anse Praslin         SC
35     SC-26   Ile Perseverance I         SC
36     SC-27  Ile Perseverance II         SC
37     SC-15             La Digue         SC
38     SC-24         Les Mamelles         SC
39     SC-17          Mont Buxton         SC
40     SC-18          Mont Fleuri         SC
41     SC-19            Plaisance         SC
42     SC-20         Pointe Larue         SC
43     SC-21           Port Glaud         SC
44     SC-25         Roche Caiman         SC
45     SC-22          Saint Louis         SC
46     SC-23             Takamaka         SC

### City table

In [1673]:
locations_df = pd.read_excel('location.xlsx')
locations_df.rename(columns={'region':'region_name', 'city':'city_name', 'localArea':'localarea_name', 'station':'station_name', 'depthMin':'depth_min', 'depthMax':'depth_max'}, inplace=True)

In [1674]:
location = pd.merge(regions_df[['region_id', 'region_name']], locations_df, on=['region_name'])
location

,region_id,region_name,country,city_name,localarea_name,station_name,latitude,longitude,depth_min,depth_max
0,MZ-G,Gaza,Mozambique,Really,Still lead,Bit its,-33.4402,3.32940,12,23
1,MZ-G,Gaza,Mozambique,Really,Different phone,Them enough,-56.7752,-78.47259,4,14
2,MZ-G,Gaza,Mozambique,Really,Still lead,Life hand,-34.1102,2.60760,10,15
3,MZ-G,Gaza,Mozambique,Really,Different phone,Politics majority,-56.8909,-78.72570,6,14
4,MZ-G,Gaza,Mozambique,Really,Still lead,Bit its,-33.3883,3.42460,10,15
5,MZ-G,Gaza,Mozambique,Really,Different phone,Them enough,-56.7285,-78.40270,0,11
6,MZ-G,Gaza,Mozambique,Really,Still lead,Life hand,-34.0952,2.62160,3,12
7,MZ-G,Gaza,Mozambique,Really,Different phone,Politics majority,-56.8013,-78.62950,11,17
8,MZ-G,Gaza,Mozambique,Really,Still lead,Bit its,-33.4402,3.32940,12,23
9,MZ-G,Gaza,Mozambique,Really,Different phone,Them enough,-56.7752,-78.47259,4,14
10,MZ-G,Gaza,Mozambique,Really,Still lead,Life hand,-34.1102,2.60760,10,15
11,MZ-G,Gaza,Mozambique,Really,Different phone,Politics majority,-56.8909,-78.72570,6,14
12,MZ-G,Gaza,Mozambique,Really,Still lead,Bit its,-33.3883,3.42460,10,15
13,MZ-G,Gaza,Mozambique,Really,Different phone,Them enough,-56.7285,-78.40270,0,11
14,MZ-G,Gaza,Mozambique,Really,Still lead,Life hand,-34.0952,2.62160,3,12
15,MZ-G,Gaza,Mozambique,Really,Different phone,Politics majority,-56.8013,-78.62950,11,17
16,MZ-G,Gaza,Mozambique,Really,Still lead,Bit its,-33.4402,3.32940,12,23
17,ZA-EC,Eastern Cape,South Africa,Race,When risk,Thousand person,83.9616,-21.33626,11,18
18,ZA-EC,Eastern Cape,South Africa,Race,Language north,Many include,-88.6515,147.95135,0,9
19,ZA-EC,Eastern Cape,South Africa,Race,When risk,Church second,83.0223,-21.91850,15,28
20,ZA-EC,Eastern Cape,South Africa,Race,Language north,Happy set,-89.3231,147.86740,3,7
21,ZA-EC,Eastern Cape,South Africa,Race,When risk,Thousand person,83.9633,-21.23760,15,22
22,ZA-EC,Eastern Cape,South Africa,Race,Language north,Many include,-88.6051,147.96040,14,19
23,ZA-EC,Eastern Cape,South Africa,Race,When risk,Church second,83.0288,-21.86440,2,14
24,ZA-EC,Eastern Cape,South Africa,Race,Language north,Happy set,-89.2652,147.89440,2,16
25,ZA-EC,Eastern Cape,South Africa,Race,When risk,Thousand person,83.9616,-21.33626,11,18
26,ZA-EC,Eastern Cape,South Africa,Race,Language north,Many include,-88.6515,147.95135,0,9
27,ZA-EC,Eastern Cape,South Africa,Race,When risk,Church second,83.0223,-21.91850,15,28
28,ZA-EC,Eastern Cape,South Africa,Race,Language north,Happy set,-89.3231,147.86740,3,7
29,ZA-EC,Eastern Cape,South Africa,Race,When risk,Thousand person,83.9633,-21.23760,15,22
30,ZA-EC,Eastern Cape,South Africa,Race,Language north,Many include,-88.6051,147.96040,14,19
31,ZA-EC,Eastern Cape,South Africa,Race,When risk,Church second,83.0288,-21.86440,2,14
32,SC-09,Bel Air,Seychelles,Include,Hot sound,Girl study,13.9299,72.47976,3,18
33,SC-09,Bel Air,Seychelles,Include,American trade,Shake son,73.4614,-128.86145,0,13
34,SC-09,Bel Air,Seychelles,Include,Hot sound,Develop public,13.8967,71.52690,9,22
35,SC-09,Bel Air,Seychelles,Include,American trade,Do rule,72.7324,-129.36810,12,17
36,SC-09,Bel Air,Seychelles,Include,Hot sound,Girl study,13.9312,72.49340,9,15
37,SC-09,Bel Air,Seychelles,Include,American trade,Shake son,73.5412,-128.79600,11,19
38,SC-09,Bel Air,Seychelles,Include,Hot sound,Develop public,13.9136,71.58080,10,15
39,SC-09,Bel Air,Seychelles,Include,American trade,Do rule,72.7755,-129.35330,10,25
40,SC-09,Bel Air,Seychelles,Include,Hot sound,Girl study,13.9299,72.47976,3,18
41,SC-09,Bel Air,Seychelles,Include,American trade,Shake son,73.4614,-128.86145,0,13
42,SC-09,Bel Air,Seychelles,Include,Hot sound,Develop public,13.8967,71.52690,9,22
43,SC-09,Bel Air,Seychelles,Include,American trade,Do rule,72.7324,-129.36810,12,17

In [1675]:
city_df = location[['region_id', 'city_name']]
city_df.drop_duplicates(inplace=True, ignore_index=True)
city_df.insert(0, 'city_id', range(1, len(city_df) + 1))
city_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\1098435287.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_df.drop_duplicates(inplace=True, ignore_index=True)

   city_id region_id city_name
0        1      MZ-G    Really
1        2     ZA-EC      Race
2        3     SC-09   Include

### Localarea table

In [1676]:
location = pd.merge(city_df[['city_id', 'city_name']], locations_df, on=['city_name'])
location

,city_id,city_name,country,region_name,localarea_name,station_name,latitude,longitude,depth_min,depth_max
0,1,Really,Mozambique,Gaza,Still lead,Bit its,-33.4402,3.32940,12,23
1,1,Really,Mozambique,Gaza,Different phone,Them enough,-56.7752,-78.47259,4,14
2,1,Really,Mozambique,Gaza,Still lead,Life hand,-34.1102,2.60760,10,15
3,1,Really,Mozambique,Gaza,Different phone,Politics majority,-56.8909,-78.72570,6,14
4,1,Really,Mozambique,Gaza,Still lead,Bit its,-33.3883,3.42460,10,15
5,1,Really,Mozambique,Gaza,Different phone,Them enough,-56.7285,-78.40270,0,11
6,1,Really,Mozambique,Gaza,Still lead,Life hand,-34.0952,2.62160,3,12
7,1,Really,Mozambique,Gaza,Different phone,Politics majority,-56.8013,-78.62950,11,17
8,1,Really,Mozambique,Gaza,Still lead,Bit its,-33.4402,3.32940,12,23
9,1,Really,Mozambique,Gaza,Different phone,Them enough,-56.7752,-78.47259,4,14
10,1,Really,Mozambique,Gaza,Still lead,Life hand,-34.1102,2.60760,10,15
11,1,Really,Mozambique,Gaza,Different phone,Politics majority,-56.8909,-78.72570,6,14
12,1,Really,Mozambique,Gaza,Still lead,Bit its,-33.3883,3.42460,10,15
13,1,Really,Mozambique,Gaza,Different phone,Them enough,-56.7285,-78.40270,0,11
14,1,Really,Mozambique,Gaza,Still lead,Life hand,-34.0952,2.62160,3,12
15,1,Really,Mozambique,Gaza,Different phone,Politics majority,-56.8013,-78.62950,11,17
16,1,Really,Mozambique,Gaza,Still lead,Bit its,-33.4402,3.32940,12,23
17,2,Race,South Africa,Eastern Cape,When risk,Thousand person,83.9616,-21.33626,11,18
18,2,Race,South Africa,Eastern Cape,Language north,Many include,-88.6515,147.95135,0,9
19,2,Race,South Africa,Eastern Cape,When risk,Church second,83.0223,-21.91850,15,28
20,2,Race,South Africa,Eastern Cape,Language north,Happy set,-89.3231,147.86740,3,7
21,2,Race,South Africa,Eastern Cape,When risk,Thousand person,83.9633,-21.23760,15,22
22,2,Race,South Africa,Eastern Cape,Language north,Many include,-88.6051,147.96040,14,19
23,2,Race,South Africa,Eastern Cape,When risk,Church second,83.0288,-21.86440,2,14
24,2,Race,South Africa,Eastern Cape,Language north,Happy set,-89.2652,147.89440,2,16
25,2,Race,South Africa,Eastern Cape,When risk,Thousand person,83.9616,-21.33626,11,18
26,2,Race,South Africa,Eastern Cape,Language north,Many include,-88.6515,147.95135,0,9
27,2,Race,South Africa,Eastern Cape,When risk,Church second,83.0223,-21.91850,15,28
28,2,Race,South Africa,Eastern Cape,Language north,Happy set,-89.3231,147.86740,3,7
29,2,Race,South Africa,Eastern Cape,When risk,Thousand person,83.9633,-21.23760,15,22
30,2,Race,South Africa,Eastern Cape,Language north,Many include,-88.6051,147.96040,14,19
31,2,Race,South Africa,Eastern Cape,When risk,Church second,83.0288,-21.86440,2,14
32,3,Include,Seychelles,Bel Air,Hot sound,Girl study,13.9299,72.47976,3,18
33,3,Include,Seychelles,Bel Air,American trade,Shake son,73.4614,-128.86145,0,13
34,3,Include,Seychelles,Bel Air,Hot sound,Develop public,13.8967,71.52690,9,22
35,3,Include,Seychelles,Bel Air,American trade,Do rule,72.7324,-129.36810,12,17
36,3,Include,Seychelles,Bel Air,Hot sound,Girl study,13.9312,72.49340,9,15
37,3,Include,Seychelles,Bel Air,American trade,Shake son,73.5412,-128.79600,11,19
38,3,Include,Seychelles,Bel Air,Hot sound,Develop public,13.9136,71.58080,10,15
39,3,Include,Seychelles,Bel Air,American trade,Do rule,72.7755,-129.35330,10,25
40,3,Include,Seychelles,Bel Air,Hot sound,Girl study,13.9299,72.47976,3,18
41,3,Include,Seychelles,Bel Air,American trade,Shake son,73.4614,-128.86145,0,13
42,3,Include,Seychelles,Bel Air,Hot sound,Develop public,13.8967,71.52690,9,22
43,3,Include,Seychelles,Bel Air,American trade,Do rule,72.7324,-129.36810,12,17

In [1677]:
localarea_df = location[['city_id', 'localarea_name']]
localarea_df.drop_duplicates(inplace=True, ignore_index=True)
localarea_df.insert(0, 'localarea_id', range(1, len(localarea_df) + 1))
localarea_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\3933648646.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  localarea_df.drop_duplicates(inplace=True, ignore_index=True)

   localarea_id  city_id   localarea_name
0             1        1       Still lead
1             2        1  Different phone
2             3        2        When risk
3             4        2   Language north
4             5        3        Hot sound
5             6        3   American trade

### Station table

In [1678]:
location = pd.merge(localarea_df[['localarea_id', 'localarea_name']], locations_df, on=['localarea_name'])
location

,localarea_id,localarea_name,country,region_name,city_name,station_name,latitude,longitude,depth_min,depth_max
0,1,Still lead,Mozambique,Gaza,Really,Bit its,-33.4402,3.32940,12,23
1,1,Still lead,Mozambique,Gaza,Really,Life hand,-34.1102,2.60760,10,15
2,1,Still lead,Mozambique,Gaza,Really,Bit its,-33.3883,3.42460,10,15
3,1,Still lead,Mozambique,Gaza,Really,Life hand,-34.0952,2.62160,3,12
4,1,Still lead,Mozambique,Gaza,Really,Bit its,-33.4402,3.32940,12,23
5,1,Still lead,Mozambique,Gaza,Really,Life hand,-34.1102,2.60760,10,15
6,1,Still lead,Mozambique,Gaza,Really,Bit its,-33.3883,3.42460,10,15
7,1,Still lead,Mozambique,Gaza,Really,Life hand,-34.0952,2.62160,3,12
8,1,Still lead,Mozambique,Gaza,Really,Bit its,-33.4402,3.32940,12,23
9,2,Different phone,Mozambique,Gaza,Really,Them enough,-56.7752,-78.47259,4,14
10,2,Different phone,Mozambique,Gaza,Really,Politics majority,-56.8909,-78.72570,6,14
11,2,Different phone,Mozambique,Gaza,Really,Them enough,-56.7285,-78.40270,0,11
12,2,Different phone,Mozambique,Gaza,Really,Politics majority,-56.8013,-78.62950,11,17
13,2,Different phone,Mozambique,Gaza,Really,Them enough,-56.7752,-78.47259,4,14
14,2,Different phone,Mozambique,Gaza,Really,Politics majority,-56.8909,-78.72570,6,14
15,2,Different phone,Mozambique,Gaza,Really,Them enough,-56.7285,-78.40270,0,11
16,2,Different phone,Mozambique,Gaza,Really,Politics majority,-56.8013,-78.62950,11,17
17,3,When risk,South Africa,Eastern Cape,Race,Thousand person,83.9616,-21.33626,11,18
18,3,When risk,South Africa,Eastern Cape,Race,Church second,83.0223,-21.91850,15,28
19,3,When risk,South Africa,Eastern Cape,Race,Thousand person,83.9633,-21.23760,15,22
20,3,When risk,South Africa,Eastern Cape,Race,Church second,83.0288,-21.86440,2,14
21,3,When risk,South Africa,Eastern Cape,Race,Thousand person,83.9616,-21.33626,11,18
22,3,When risk,South Africa,Eastern Cape,Race,Church second,83.0223,-21.91850,15,28
23,3,When risk,South Africa,Eastern Cape,Race,Thousand person,83.9633,-21.23760,15,22
24,3,When risk,South Africa,Eastern Cape,Race,Church second,83.0288,-21.86440,2,14
25,4,Language north,South Africa,Eastern Cape,Race,Many include,-88.6515,147.95135,0,9
26,4,Language north,South Africa,Eastern Cape,Race,Happy set,-89.3231,147.86740,3,7
27,4,Language north,South Africa,Eastern Cape,Race,Many include,-88.6051,147.96040,14,19
28,4,Language north,South Africa,Eastern Cape,Race,Happy set,-89.2652,147.89440,2,16
29,4,Language north,South Africa,Eastern Cape,Race,Many include,-88.6515,147.95135,0,9
30,4,Language north,South Africa,Eastern Cape,Race,Happy set,-89.3231,147.86740,3,7
31,4,Language north,South Africa,Eastern Cape,Race,Many include,-88.6051,147.96040,14,19
32,5,Hot sound,Seychelles,Bel Air,Include,Girl study,13.9299,72.47976,3,18
33,5,Hot sound,Seychelles,Bel Air,Include,Develop public,13.8967,71.52690,9,22
34,5,Hot sound,Seychelles,Bel Air,Include,Girl study,13.9312,72.49340,9,15
35,5,Hot sound,Seychelles,Bel Air,Include,Develop public,13.9136,71.58080,10,15
36,5,Hot sound,Seychelles,Bel Air,Include,Girl study,13.9299,72.47976,3,18
37,5,Hot sound,Seychelles,Bel Air,Include,Develop public,13.8967,71.52690,9,22
38,6,American trade,Seychelles,Bel Air,Include,Shake son,73.4614,-128.86145,0,13
39,6,American trade,Seychelles,Bel Air,Include,Do rule,72.7324,-129.36810,12,17
40,6,American trade,Seychelles,Bel Air,Include,Shake son,73.5412,-128.79600,11,19
41,6,American trade,Seychelles,Bel Air,Include,Do rule,72.7755,-129.35330,10,25
42,6,American trade,Seychelles,Bel Air,Include,Shake son,73.4614,-128.86145,0,13
43,6,American trade,Seychelles,Bel Air,Include,Do rule,72.7324,-129.36810,12,17

In [1679]:
station_df = location[['localarea_id', 'station_name']]
station_df.drop_duplicates(inplace=True, ignore_index=True)
station_df.insert(0, 'station_id', range(1, len(station_df) + 1))
station_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\2520341363.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  station_df.drop_duplicates(inplace=True, ignore_index=True)

    station_id  localarea_id       station_name
0            1             1            Bit its
1            2             1          Life hand
2            3             2        Them enough
3            4             2  Politics majority
4            5             3    Thousand person
5            6             3      Church second
6            7             4       Many include
7            8             4          Happy set
8            9             5         Girl study
9           10             5     Develop public
10          11             6          Shake son
11          12             6            Do rule

### Site table

In [1680]:
location = pd.merge(station_df[['station_id', 'station_name']], locations_df, on=['station_name'])
location

,station_id,station_name,country,region_name,city_name,localarea_name,latitude,longitude,depth_min,depth_max
0,1,Bit its,Mozambique,Gaza,Really,Still lead,-33.4402,3.32940,12,23
1,1,Bit its,Mozambique,Gaza,Really,Still lead,-33.3883,3.42460,10,15
2,1,Bit its,Mozambique,Gaza,Really,Still lead,-33.4402,3.32940,12,23
3,1,Bit its,Mozambique,Gaza,Really,Still lead,-33.3883,3.42460,10,15
4,1,Bit its,Mozambique,Gaza,Really,Still lead,-33.4402,3.32940,12,23
5,2,Life hand,Mozambique,Gaza,Really,Still lead,-34.1102,2.60760,10,15
6,2,Life hand,Mozambique,Gaza,Really,Still lead,-34.0952,2.62160,3,12
7,2,Life hand,Mozambique,Gaza,Really,Still lead,-34.1102,2.60760,10,15
8,2,Life hand,Mozambique,Gaza,Really,Still lead,-34.0952,2.62160,3,12
9,3,Them enough,Mozambique,Gaza,Really,Different phone,-56.7752,-78.47259,4,14
10,3,Them enough,Mozambique,Gaza,Really,Different phone,-56.7285,-78.40270,0,11
11,3,Them enough,Mozambique,Gaza,Really,Different phone,-56.7752,-78.47259,4,14
12,3,Them enough,Mozambique,Gaza,Really,Different phone,-56.7285,-78.40270,0,11
13,4,Politics majority,Mozambique,Gaza,Really,Different phone,-56.8909,-78.72570,6,14
14,4,Politics majority,Mozambique,Gaza,Really,Different phone,-56.8013,-78.62950,11,17
15,4,Politics majority,Mozambique,Gaza,Really,Different phone,-56.8909,-78.72570,6,14
16,4,Politics majority,Mozambique,Gaza,Really,Different phone,-56.8013,-78.62950,11,17
17,5,Thousand person,South Africa,Eastern Cape,Race,When risk,83.9616,-21.33626,11,18
18,5,Thousand person,South Africa,Eastern Cape,Race,When risk,83.9633,-21.23760,15,22
19,5,Thousand person,South Africa,Eastern Cape,Race,When risk,83.9616,-21.33626,11,18
20,5,Thousand person,South Africa,Eastern Cape,Race,When risk,83.9633,-21.23760,15,22
21,6,Church second,South Africa,Eastern Cape,Race,When risk,83.0223,-21.91850,15,28
22,6,Church second,South Africa,Eastern Cape,Race,When risk,83.0288,-21.86440,2,14
23,6,Church second,South Africa,Eastern Cape,Race,When risk,83.0223,-21.91850,15,28
24,6,Church second,South Africa,Eastern Cape,Race,When risk,83.0288,-21.86440,2,14
25,7,Many include,South Africa,Eastern Cape,Race,Language north,-88.6515,147.95135,0,9
26,7,Many include,South Africa,Eastern Cape,Race,Language north,-88.6051,147.96040,14,19
27,7,Many include,South Africa,Eastern Cape,Race,Language north,-88.6515,147.95135,0,9
28,7,Many include,South Africa,Eastern Cape,Race,Language north,-88.6051,147.96040,14,19
29,8,Happy set,South Africa,Eastern Cape,Race,Language north,-89.3231,147.86740,3,7
30,8,Happy set,South Africa,Eastern Cape,Race,Language north,-89.2652,147.89440,2,16
31,8,Happy set,South Africa,Eastern Cape,Race,Language north,-89.3231,147.86740,3,7
32,9,Girl study,Seychelles,Bel Air,Include,Hot sound,13.9299,72.47976,3,18
33,9,Girl study,Seychelles,Bel Air,Include,Hot sound,13.9312,72.49340,9,15
34,9,Girl study,Seychelles,Bel Air,Include,Hot sound,13.9299,72.47976,3,18
35,10,Develop public,Seychelles,Bel Air,Include,Hot sound,13.8967,71.52690,9,22
36,10,Develop public,Seychelles,Bel Air,Include,Hot sound,13.9136,71.58080,10,15
37,10,Develop public,Seychelles,Bel Air,Include,Hot sound,13.8967,71.52690,9,22
38,11,Shake son,Seychelles,Bel Air,Include,American trade,73.4614,-128.86145,0,13
39,11,Shake son,Seychelles,Bel Air,Include,American trade,73.5412,-128.79600,11,19
40,11,Shake son,Seychelles,Bel Air,Include,American trade,73.4614,-128.86145,0,13
41,12,Do rule,Seychelles,Bel Air,Include,American trade,72.7324,-129.36810,12,17
42,12,Do rule,Seychelles,Bel Air,Include,American trade,72.7755,-129.35330,10,25
43,12,Do rule,Seychelles,Bel Air,Include,American trade,72.7324,-129.36810,12,17

In [1681]:
site_df = location[['station_id', 'latitude', 'longitude', 'depth_min', 'depth_max']]
site_df.drop_duplicates(inplace=True, ignore_index=True)
site_df.insert(0, 'site_id', range(1, len(site_df) + 1))
site_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\697768879.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  site_df.drop_duplicates(inplace=True, ignore_index=True)

    site_id  station_id  latitude  longitude  depth_min  depth_max
0         1           1  -33.4402    3.32940         12         23
1         2           1  -33.3883    3.42460         10         15
2         3           2  -34.1102    2.60760         10         15
3         4           2  -34.0952    2.62160          3         12
4         5           3  -56.7752  -78.47259          4         14
5         6           3  -56.7285  -78.40270          0         11
6         7           4  -56.8909  -78.72570          6         14
7         8           4  -56.8013  -78.62950         11         17
8         9           5   83.9616  -21.33626         11         18
9        10           5   83.9633  -21.23760         15         22
10       11           6   83.0223  -21.91850         15         28
11       12           6   83.0288  -21.86440          2         14
12       13           7  -88.6515  147.95135          0          9
13       14           7  -88.6051  147.96040         14         19
14       15           8  -89.3231  147.86740          3          7
15       16           8  -89.2652  147.89440          2         16
16       17           9   13.9299   72.47976          3         18
17       18           9   13.9312   72.49340          9         15
18       19          10   13.8967   71.52690          9         22
19       20          10   13.9136   71.58080         10         15
20       21          11   73.4614 -128.86145          0         13
21       22          11   73.5412 -128.79600         11         19
22       23          12   72.7324 -129.36810         12         17
23       24          12   72.7755 -129.35330         10         25

### Collection table

In [1682]:
collection_df.rename(columns={'depthMin':'depth_min', 'depthMax':'depth_max'}, inplace=True)
collection_df

,sourceID,otherIDs,collectedDate,permitNo,country,region,city,localArea,station,latitude,...,Class,Subclass,Superorder,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species
0,TIC2041-1,NaN,30/10/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Thousand person,83.9616,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 015 RSA SPN roseum
1,TIC2041-2,NaN,21/06/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Many include,-88.6515,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
2,TIC2041-3,NaN,15/02/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Church second,83.0223,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
3,TIC2041-4,NaN,03/01/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Happy set,-89.3231,...,Demospongiae,NaN,NaN,Dictyoceratida,NaN,Ircinidae,NaN,Psammocinia,NaN,sp 001 RSA MH NMMU
4,TIC2041-5,NaN,05/02/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Thousand person,83.9633,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
5,TIC2041-6,NaN,20/12/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Many include,-88.6051,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,sp 001 RSA MKB CRRF
6,TIC2041-7,NaN,10/11/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Church second,83.0288,...,Demospongiae,NaN,NaN,Hadromerida,NaN,Clionaidae,NaN,NG Clionaidae 001 RSA MKB CRRF,NaN,sp 002 RSA SPN CRRF
7,TIC2041-8,NaN,15/08/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Happy set,-89.2652,...,Demospongiae,NaN,NaN,Hadromerida,NaN,Hemiasterellidae,NaN,Hemiasterella,NaN,sp001 thick purple fan
8,TIC2041-9,NaN,14/01/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Thousand person,83.9616,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
9,TIC2041-10,NaN,18/09/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Many include,-88.6515,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
10,TIC2041-11,NaN,27/09/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Church second,83.0223,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,sp 002 RSA SPN Peach pads
11,TIC2041-12,NaN,02/02/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Happy set,-89.3231,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
12,TIC2041-13,NaN,08/02/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Thousand person,83.9633,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Atriolum,NaN,sp 003 RSA SPN Spitspeaks
13,TIC2041-14,NaN,25/10/2041,RES2041,South Africa,Eastern Cape,Race,Language north,Many include,-88.6051,...,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 001 RSA MKB CRRF purple
14,TIC2041-15,NaN,18/05/2041,RES2041,South Africa,Eastern Cape,Race,When risk,Church second,83.0288,...,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 004 RSA SPN blue
15,MOZ42-1,NaN,02/04/2042,RES2042,Mozambique,Gaza,Really,Still lead,Bit its,-33.4402,...,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Hymeniacidon,NaN,sp 002 RSA SPN CRRF
16,MOZ42-2,NaN,07/01/2042,RES2042,Mozambique,Gaza,Really,Different phone,Them enough,-56.7752,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
17,MOZ42-3,NaN,12/01/2042,RES2042,Mozambique,Gaza,Really,Still lead,Life hand,-34.1102,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
18,MOZ42-4,NaN,03/11/2042,RES2042,Mozambique,Gaza,Really,Different phone,Politics majority,-56.8909,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
19,MOZ42-5,NaN,07/01/2042,RES2042,Mozambique,Gaza,Really,Still lead,Bit its,-33.3883,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 003 SPN RSA Gigglegrey
20,MOZ42-6,NaN,15/05/2042,RES2042,Mozambique,Gaza,Really,Different phone,Them enough,-56.7285,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
21,MOZ42-7,NaN,09/09/2042,RES2042,Mozambique,Gaza,Really,Still lead,Life hand,-34.0952,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
22,MOZ42-8,NaN,31/08/2042,RES2042,Mozambique,Gaza,Really,Different phone,Politics majority,-56.8013,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 005 RSA
23,MOZ42-9,NaN,08/07/2042,RES2042,Mozambique,Gaza,Really,Still lead,Bit its,-33.4402,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
24,MOZ42-10,NaN,28/08/2042,RES2042,Mozambique,Gaza,Really,Different phone,Them enough,-56.7752,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,dellachiajei
25,MOZ42-11,NaN,30/06/2042,RES2042,Mozambique,Gaza,Really,Still lead,Life hand,-34.1102,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
26,MOZ42-12,NaN,27/02/2042,RES2042,Mozambique,Gaza,Really,Different phone,Politics majority,-56.8909,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Polysyncraton,NaN,magnilarvum
27,MOZ42-13,NaN,05/02/2042,RES2042,Mozambique,Gaza,Really,Still lead,Bit its,-33.3883,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 008 SPN RSA Peachtip
28,MOZ42-14,NaN,13/03/2042,RES2042,Mozambique,Gaza,Really,Different phone,Them enough,-56.7285,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polyclinidae,NaN,Aplidiopsis,NaN,sp 001 RSA SPN Firm dark large
29,MOZ42-15,NaN,05/10/2042,RES2042,Mozambique,Gaza,Really,Still lead,Life hand,-34.0952,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
30,MOZ42-16,NaN,14/02/2042,RES2042,Mozambique,Gaza,Really,Different phone,Politics majority,-56.8013,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
31,MOZ42-17,NaN,25/11/2042,RES2042,Mozambique,Gaza,Really,Still lead,Bit its,-33.4402,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
32,SAF43-1,NaN,06/01/2043,RES2043,Seychelles,Bel Air,Include,Hot sound,Girl study,13.9299,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
33,SAF43-2,NaN,15/07/2043,RES2043,Seychelles,Bel Air,Include,American trade,Shake son,73.4614,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
34,SAF43-3,NaN,09/07/2043,RES2043,Seychelles,Bel Air,Include,Hot sound,Develop public,13.8967,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
35,SAF43-4,NaN,08/12/2043,RES2043,Seychelles,Bel Air,Include,American trade,Do rule,72.7324,...,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Thalysias,oxitoxa
36,SAF43-5,NaN,08/04/2043,RES2043,Seychelles,Bel Air,Include,Hot sound,Girl study,13.9312,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
37,SAF43-6,NaN,26/01/2043,RES2043,Seychelles,Bel Air,Include,American trade,Shake son,73.5412,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
38,SAF43-7,NaN,17/09/2043,RES2043,Seychelles,Bel Air,Include,Hot sound,Develop public,13.9136,...,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Ciocalypta,NaN,sp 001 RSA MKB CRRF
39,SAF43-8,NaN,30/07/2043,RES2043,Seychelles,Bel Air,Include,American trade,Do rule,72.7755,...,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Axosuberites,sp 001 RSA MKB CRRF mesh
40,SAF43-9,NaN,21/12/2043,RES2043,Seychelles,Bel Air,Include,Hot sound,Girl study,13.9299,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
41,SAF43-10,NaN,30/06/2043,RES2043,Seychelles,Bel Air,Include,American trade,Shake son,73.4614,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
42,SAF43-11,NaN,27/01/2043,RES2043,Seychelles,Bel Air,Include,Hot sound,Develop public,13.8967,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
43,SAF43-12,NaN,22/08/2043,RES2043,Seychelles,Bel Air,Include,American trade,Do rule,72.7324,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata

In [1683]:
# Include site_id
collection = pd.merge(site_df[['site_id', 'latitude', 'longitude', 'depth_min', 'depth_max']], collection_df, on=['latitude', 'longitude', 'depth_min', 'depth_max'])
collection

,site_id,latitude,longitude,depth_min,depth_max,sourceID,otherIDs,collectedDate,permitNo,country,...,Class,Subclass,Superorder,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species
0,1,-33.4402,3.32940,12,23,MOZ42-1,NaN,02/04/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Hymeniacidon,NaN,sp 002 RSA SPN CRRF
1,1,-33.4402,3.32940,12,23,MOZ42-9,NaN,08/07/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
2,1,-33.4402,3.32940,12,23,MOZ42-17,NaN,25/11/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
3,2,-33.3883,3.42460,10,15,MOZ42-5,NaN,07/01/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 003 SPN RSA Gigglegrey
4,2,-33.3883,3.42460,10,15,MOZ42-13,NaN,05/02/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 008 SPN RSA Peachtip
5,3,-34.1102,2.60760,10,15,MOZ42-3,NaN,12/01/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
6,3,-34.1102,2.60760,10,15,MOZ42-11,NaN,30/06/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
7,4,-34.0952,2.62160,3,12,MOZ42-7,NaN,09/09/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
8,4,-34.0952,2.62160,3,12,MOZ42-15,NaN,05/10/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
9,5,-56.7752,-78.47259,4,14,MOZ42-2,NaN,07/01/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
10,5,-56.7752,-78.47259,4,14,MOZ42-10,NaN,28/08/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,dellachiajei
11,6,-56.7285,-78.40270,0,11,MOZ42-6,NaN,15/05/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
12,6,-56.7285,-78.40270,0,11,MOZ42-14,NaN,13/03/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polyclinidae,NaN,Aplidiopsis,NaN,sp 001 RSA SPN Firm dark large
13,7,-56.8909,-78.72570,6,14,MOZ42-4,NaN,03/11/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
14,7,-56.8909,-78.72570,6,14,MOZ42-12,NaN,27/02/2042,RES2042,Mozambique,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Polysyncraton,NaN,magnilarvum
15,8,-56.8013,-78.62950,11,17,MOZ42-8,NaN,31/08/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 005 RSA
16,8,-56.8013,-78.62950,11,17,MOZ42-16,NaN,14/02/2042,RES2042,Mozambique,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
17,9,83.9616,-21.33626,11,18,TIC2041-1,NaN,30/10/2041,RES2041,South Africa,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 015 RSA SPN roseum
18,9,83.9616,-21.33626,11,18,TIC2041-9,NaN,14/01/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
19,10,83.9633,-21.23760,15,22,TIC2041-5,NaN,05/02/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
20,10,83.9633,-21.23760,15,22,TIC2041-13,NaN,08/02/2041,RES2041,South Africa,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Atriolum,NaN,sp 003 RSA SPN Spitspeaks
21,11,83.0223,-21.91850,15,28,TIC2041-3,NaN,15/02/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
22,11,83.0223,-21.91850,15,28,TIC2041-11,NaN,27/09/2041,RES2041,South Africa,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,sp 002 RSA SPN Peach pads
23,12,83.0288,-21.86440,2,14,TIC2041-7,NaN,10/11/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Hadromerida,NaN,Clionaidae,NaN,NG Clionaidae 001 RSA MKB CRRF,NaN,sp 002 RSA SPN CRRF
24,12,83.0288,-21.86440,2,14,TIC2041-15,NaN,18/05/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 004 RSA SPN blue
25,13,-88.6515,147.95135,0,9,TIC2041-2,NaN,21/06/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
26,13,-88.6515,147.95135,0,9,TIC2041-10,NaN,18/09/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
27,14,-88.6051,147.96040,14,19,TIC2041-6,NaN,20/12/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,sp 001 RSA MKB CRRF
28,14,-88.6051,147.96040,14,19,TIC2041-14,NaN,25/10/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 001 RSA MKB CRRF purple
29,15,-89.3231,147.86740,3,7,TIC2041-4,NaN,03/01/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Dictyoceratida,NaN,Ircinidae,NaN,Psammocinia,NaN,sp 001 RSA MH NMMU
30,15,-89.3231,147.86740,3,7,TIC2041-12,NaN,02/02/2041,RES2041,South Africa,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
31,16,-89.2652,147.89440,2,16,TIC2041-8,NaN,15/08/2041,RES2041,South Africa,...,Demospongiae,NaN,NaN,Hadromerida,NaN,Hemiasterellidae,NaN,Hemiasterella,NaN,sp001 thick purple fan
32,17,13.9299,72.47976,3,18,SAF43-1,NaN,06/01/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
33,17,13.9299,72.47976,3,18,SAF43-9,NaN,21/12/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
34,18,13.9312,72.49340,9,15,SAF43-5,NaN,08/04/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
35,19,13.8967,71.52690,9,22,SAF43-3,NaN,09/07/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
36,19,13.8967,71.52690,9,22,SAF43-11,NaN,27/01/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
37,20,13.9136,71.58080,10,15,SAF43-7,NaN,17/09/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Ciocalypta,NaN,sp 001 RSA MKB CRRF
38,21,73.4614,-128.86145,0,13,SAF43-2,NaN,15/07/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
39,21,73.4614,-128.86145,0,13,SAF43-10,NaN,30/06/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
40,22,73.5412,-128.79600,11,19,SAF43-6,NaN,26/01/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
41,23,72.7324,-129.36810,12,17,SAF43-4,NaN,08/12/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Thalysias,oxitoxa
42,23,72.7324,-129.36810,12,17,SAF43-12,NaN,22/08/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
43,24,72.7755,-129.35330,10,25,SAF43-8,NaN,30/07/2043,RES2043,Seychelles,...,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Axosuberites,sp 001 RSA MKB CRRF mesh

In [1684]:
# Remove Country to depth_max info
collection.drop(['country', 'region', 'city', 'localArea', 'station', 'latitude', 'longitude', 'depth_min', 'depth_max'], axis=1, inplace=True)
collection.rename(columns={'sourceID':'sample_id', 'otherIDs':'other_ids', 'collectedDate':'date_collected', 'permitNo':'permit_no', 'collectedBy':'collected_by', 'identifiedBy':'identified_by',
    'otherDescription':'other_description'}, inplace=True)
collection

,site_id,sample_id,other_ids,date_collected,permit_no,collected_by,identified_by,classification,other_description,Kingdom,...,Class,Subclass,Superorder,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species
0,1,MOZ42-1,NaN,02/04/2042,RES2042,Clive Morrison,Clive Morrison,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Hymeniacidon,NaN,sp 002 RSA SPN CRRF
1,1,MOZ42-9,NaN,08/07/2042,RES2042,Mandy Peterson and Clive Morrison,Harry Warner,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
2,1,MOZ42-17,NaN,25/11/2042,RES2042,Mandy Peterson; Trevor Andrews,Clive Morrison,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
3,2,MOZ42-5,NaN,07/01/2042,RES2042,Trevor Andrews,Harry Warner,Complete,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 003 SPN RSA Gigglegrey
4,2,MOZ42-13,NaN,05/02/2042,RES2042,Trevor Andrews; Mandy Peterson,Harry Warner,Questionable,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 008 SPN RSA Peachtip
5,3,MOZ42-3,NaN,12/01/2042,RES2042,Clive Morrison,Clive Morrison,Complete,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
6,3,MOZ42-11,NaN,30/06/2042,RES2042,Trevor Andrews; Mandy Peterson,Clive Morrison,Complete,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
7,4,MOZ42-7,NaN,09/09/2042,RES2042,Trevor Andrews and Clive Morrison,Harry Warner,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
8,4,MOZ42-15,NaN,05/10/2042,RES2042,Trevor Andrews; Mandy Peterson,Harry Warner,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
9,5,MOZ42-2,NaN,07/01/2042,RES2042,Clive Morrison and Mandy Peterson,Clive Morrison,Tentative,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
10,5,MOZ42-10,NaN,28/08/2042,RES2042,Clive Morrison and Trevor Andrews,Clive Morrison,Complete,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,dellachiajei
11,6,MOZ42-6,NaN,15/05/2042,RES2042,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
12,6,MOZ42-14,NaN,13/03/2042,RES2042,Mandy Peterson and Clive Morrison,Clive Morrison,Tentative,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polyclinidae,NaN,Aplidiopsis,NaN,sp 001 RSA SPN Firm dark large
13,7,MOZ42-4,NaN,03/11/2042,RES2042,Clive Morrison,Clive Morrison,Preliminary,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
14,7,MOZ42-12,NaN,27/02/2042,RES2042,Mandy Peterson,Harry Warner,Complete,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Polysyncraton,NaN,magnilarvum
15,8,MOZ42-8,NaN,31/08/2042,RES2042,Clive Morrison,Clive Morrison,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 005 RSA
16,8,MOZ42-16,NaN,14/02/2042,RES2042,Clive Morrison,Harry Warner,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
17,9,TIC2041-1,NaN,30/10/2041,RES2041,Trevor Andrews and Clive Morrison,Clive Morrison,Preliminary,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 015 RSA SPN roseum
18,9,TIC2041-9,NaN,14/01/2041,RES2041,Clive Morrison and Trevor Andrews,Clive Morrison,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
19,10,TIC2041-5,NaN,05/02/2041,RES2041,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
20,10,TIC2041-13,NaN,08/02/2041,RES2041,Mandy Peterson; Trevor Andrews,Harry Warner,Questionable,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Atriolum,NaN,sp 003 RSA SPN Spitspeaks
21,11,TIC2041-3,NaN,15/02/2041,RES2041,Trevor Andrews; Mandy Peterson,Harry Warner,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
22,11,TIC2041-11,NaN,27/09/2041,RES2041,Trevor Andrews,Clive Morrison,Questionable,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,sp 002 RSA SPN Peach pads
23,12,TIC2041-7,NaN,10/11/2041,RES2041,Mandy Peterson and Clive Morrison,Harry Warner,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Hadromerida,NaN,Clionaidae,NaN,NG Clionaidae 001 RSA MKB CRRF,NaN,sp 002 RSA SPN CRRF
24,12,TIC2041-15,NaN,18/05/2041,RES2041,Mandy Peterson and Clive Morrison,Harry Warner,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 004 RSA SPN blue
25,13,TIC2041-2,NaN,21/06/2041,RES2041,Clive Morrison,Clive Morrison,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
26,13,TIC2041-10,NaN,18/09/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
27,14,TIC2041-6,NaN,20/12/2041,RES2041,Clive Morrison,Harry Warner,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,sp 001 RSA MKB CRRF
28,14,TIC2041-14,NaN,25/10/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 001 RSA MKB CRRF purple
29,15,TIC2041-4,NaN,03/01/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Dictyoceratida,NaN,Ircinidae,NaN,Psammocinia,NaN,sp 001 RSA MH NMMU
30,15,TIC2041-12,NaN,02/02/2041,RES2041,Clive Morrison,Harry Warner,Tentative,NaN,Animalia,...,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
31,16,TIC2041-8,NaN,15/08/2041,RES2041,Trevor Andrews,Clive Morrison,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Hadromerida,NaN,Hemiasterellidae,NaN,Hemiasterella,NaN,sp001 thick purple fan
32,17,SAF43-1,NaN,06/01/2043,RES2043,Mandy Peterson,Clive Morrison,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
33,17,SAF43-9,NaN,21/12/2043,RES2043,Mandy Peterson; Trevor Andrews,Clive Morrison,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
34,18,SAF43-5,NaN,08/04/2043,RES2043,Trevor Andrews; Mandy Peterson,Clive Morrison,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
35,19,SAF43-3,NaN,09/07/2043,RES2043,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
36,19,SAF43-11,NaN,27/01/2043,RES2043,Trevor Andrews; Mandy Peterson,Harry Warner,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
37,20,SAF43-7,NaN,17/09/2043,RES2043,Mandy Peterson; Trevor Andrews,Clive Morrison,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Ciocalypta,NaN,sp 001 RSA MKB CRRF
38,21,SAF43-2,NaN,15/07/2043,RES2043,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
39,21,SAF43-10,NaN,30/06/2043,RES2043,Clive Morrison and Mandy Peterson,Harry Warner,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
40,22,SAF43-6,NaN,26/01/2043,RES2043,Mandy Peterson; Trevor Andrews,Harry Warner,Complete,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
41,23,SAF43-4,NaN,08/12/2043,RES2043,Trevor Andrews; Mandy Peterson,Clive Morrison,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Thalysias,oxitoxa
42,23,SAF43-12,NaN,22/08/2043,RES2043,Mandy Peterson; Trevor Andrews,Harry Warner,Preliminary,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
43,24,SAF43-8,NaN,30/07/2043,RES2043,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,NaN,Animalia,...,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Axosuberites,sp 001 RSA MKB CRRF mesh

### Taxonomy tables

In [1685]:
tax_df = pd.read_excel("taxonomy.xlsx")
tax_df = tax_df.head(len(collection))
tax_df

,Kingdom,Phylum,Subphylum,Class,Subclass,Superorder,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species
0,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 015 RSA SPN roseum
1,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
2,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
3,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Dictyoceratida,NaN,Ircinidae,NaN,Psammocinia,NaN,sp 001 RSA MH NMMU
4,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 004 RSA nguni
5,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,sp 001 RSA MKB CRRF
6,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Hadromerida,NaN,Clionaidae,NaN,NG Clionaidae 001 RSA MKB CRRF,NaN,sp 002 RSA SPN CRRF
7,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Hadromerida,NaN,Hemiasterellidae,NaN,Hemiasterella,NaN,sp001 thick purple fan
8,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN,bellae
9,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
10,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,sp 002 RSA SPN Peach pads
11,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
12,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Atriolum,NaN,sp 003 RSA SPN Spitspeaks
13,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 001 RSA MKB CRRF purple
14,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona,sp 004 RSA SPN blue
15,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Hymeniacidon,NaN,sp 002 RSA SPN CRRF
16,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
17,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 005 SPN RSA Redwhitetongue
18,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 002 SPN RSA Custardbrain
19,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 003 SPN RSA Gigglegrey
20,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
21,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
22,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 005 RSA
23,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 001 RSA toufieki
24,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN,dellachiajei
25,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN,sp 006 RSA SPN Brightorangecrust
26,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Polysyncraton,NaN,magnilarvum
27,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN,sp 008 SPN RSA Peachtip
28,Animalia,Chordata,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polyclinidae,NaN,Aplidiopsis,NaN,sp 001 RSA SPN Firm dark large
29,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
30,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
31,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
32,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
33,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
34,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
35,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Thalysias,oxitoxa
36,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
37,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,sp 002 RSA michaeli
38,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Ciocalypta,NaN,sp 001 RSA MKB CRRF
39,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Axosuberites,sp 001 RSA MKB CRRF mesh
40,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN,clathratus
41,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
42,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata
43,Animalia,Porifera,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN,pedunculata

In [1686]:
# Create taxonhierarchy
rank_list = list(tax_df.columns.values)
taxonhierarcy = pd.DataFrame(rank_list, columns=["rank_name"])
taxonhierarcy.insert(0, "rank_id", range(1, len(taxonhierarcy) + 1))
taxonhierarcy.insert(2, "parent_id", (taxonhierarcy["rank_id"]-1))
taxonhierarcy.loc[taxonhierarcy['parent_id'] == -1, 'parent_id'] = "NaN"
taxonhierarcy

    rank_id   rank_name parent_id
0         1     Kingdom         0
1         2      Phylum         1
2         3   Subphylum         2
3         4       Class         3
4         5    Subclass         4
5         6  Superorder         5
6         7       Order         6
7         8    Suborder         7
8         9      Family         8
9        10   Subfamily         9
10       11       Genus        10
11       12    Subgenus        11
12       13     Species        12

In [1687]:
tax_list = tax_df.values.flatten().tolist()
tax_id_list = []
parent_tax_id_list = []
rank_id_list = []
taxon_name = []
parent_pos = 0
pos = 0
for taxStr in tax_list:
    if str(taxStr) != 'nan':
        if taxStr not in taxon_name:
            taxon_name.append(taxStr)
            parent_tax_id_list.append(parent_pos)
            tax_id_list.append(len(taxon_name))
            rank_id_list.append(pos+1)
            if pos == 12:
                parent_pos = 0
            else:
                parent_pos = len(taxon_name)
        else:
            parent_pos = taxon_name.index(taxStr) + 1
        pos = (pos + 1) % 13
    else:
        pos = (pos + 1) % 13

print(parent_tax_id_list)
print(rank_id_list)
print(taxon_name)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 10, 11, 12, 13, 14, 15, 14, 17, 11, 19, 20, 21, 12, 23, 24, 25, 11, 27, 28, 29, 27, 31, 32, 17, 6, 35, 36, 8, 6, 39, 40, 11, 42, 43, 44, 45, 45, 11, 48, 49, 8, 8, 39, 53, 17, 36, 39, 57, 8, 6, 60, 61, 17, 17, 12, 65, 66, 67, 68, 69, 25, 49, 68, 73]
[1, 2, 3, 4, 6, 7, 9, 11, 13, 2, 4, 7, 8, 9, 11, 13, 11, 13, 7, 9, 11, 13, 8, 9, 11, 13, 7, 9, 11, 13, 9, 11, 13, 13, 9, 11, 13, 13, 9, 11, 13, 7, 8, 9, 11, 13, 13, 7, 9, 11, 13, 13, 11, 13, 13, 13, 11, 13, 13, 9, 11, 13, 13, 13, 8, 9, 10, 11, 12, 13, 13, 11, 12, 13]
['Animalia', 'Chordata', 'Urochordata -Tunicata', 'Ascidiacea', 'Enterogona', 'Aplousobranchia', 'Pseudodistomidae', 'Pseudodistoma', 'sp 015 RSA SPN roseum', 'Porifera', 'Demospongiae', 'Poecilosclerida', 'Latrunculina', 'Latrunculiidae', 'Cyclacanthia', 'bellae', 'Tsitsikamma', 'sp 004 RSA nguni', 'Dictyoceratida', 'Ircinidae', 'Psammocinia', 'sp 001 RSA MH NMMU', 'Myxillina', 'Hymedesmiidae', 'Phorbas', 'sp 001 RSA MKB CRRF', 'Hadromerida', 'Clionaidae', 'NG Clionaidae 001 RSA MKB CRRF', 'sp 002 RSA SPN CRRF', 'Hemiasterellidae', 'Hemiasterella', 'sp001 thick purple fan', 'sp 001 RSA toufieki', 'Polycitoridae', 'Cystodytes', 'sp 002 RSA SPN Peach pads', 'sp 005 SPN RSA Redwhitetongue', 'Didemnidae', 'Atriolum', 'sp 003 RSA SPN Spitspeaks', 'Haplosclerida', 'Haplosclerina', 'Chalinidae', 'Haliclona', 'sp 001 RSA MKB CRRF purple', 'sp 004 RSA SPN blue', 'Halichondrida', 'Halichondriidae', 'Hymeniacidon', 'sp 002 SPN RSA Custardbrain', 'sp 003 SPN RSA Gigglegrey', 'Didemnum', 'sp 006 RSA SPN Brightorangecrust', 'sp 005 RSA', 'dellachiajei', 'Polysyncraton', 'magnilarvum', 'sp 008 SPN RSA Peachtip', 'Polyclinidae', 'Aplidiopsis', 'sp 001 RSA SPN Firm dark large', 'sp 002 RSA michaeli', 'pedunculata', 'Microcionina', 'Microcionidae', 'Microcioninae', 'Clathria', 'Thalysias', 'oxitoxa', 'clathratus', 'Ciocalypta', 'Axosuberites', 'sp 001 RSA MKB CRRF mesh']

In [1688]:
taxonomy = pd.DataFrame({'taxonomy_id':tax_id_list, 'parent_taxon_id':parent_tax_id_list, 'rank_id':rank_id_list, 'taxon_name':taxon_name})
taxonomy

    taxonomy_id  parent_taxon_id  rank_id                taxon_name
0             1                0        1                  Animalia
1             2                1        2                  Chordata
2             3                2        3     Urochordata -Tunicata
3             4                3        4                Ascidiacea
4             5                4        6                Enterogona
..          ...              ...      ...                       ...
69           70               69       13                   oxitoxa
70           71               25       13                clathratus
71           72               49       11                Ciocalypta
72           73               68       12              Axosuberites
73           74               73       13  sp 001 RSA MKB CRRF mesh

[74 rows x 4 columns]

In [1689]:
# Get all species and associated taxonomy_id
species_df = taxonomy.loc[taxonomy['rank_id'] == 13]
species_df.rename(columns={'taxon_name':'Species'}, inplace=True)
species_df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\3041161045.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  species_df.rename(columns={'taxon_name':'Species'}, inplace=True)

    taxonomy_id  parent_taxon_id  rank_id                           Species
8             9                8       13             sp 015 RSA SPN roseum
15           16               15       13                            bellae
17           18               17       13                  sp 004 RSA nguni
21           22               21       13                sp 001 RSA MH NMMU
25           26               25       13               sp 001 RSA MKB CRRF
29           30               29       13               sp 002 RSA SPN CRRF
32           33               32       13            sp001 thick purple fan
33           34               17       13               sp 001 RSA toufieki
36           37               36       13         sp 002 RSA SPN Peach pads
37           38                8       13     sp 005 SPN RSA Redwhitetongue
40           41               40       13         sp 003 RSA SPN Spitspeaks
45           46               45       13        sp 001 RSA MKB CRRF purple
46           47               45       13               sp 004 RSA SPN blue
50           51                8       13       sp 002 SPN RSA Custardbrain
51           52                8       13         sp 003 SPN RSA Gigglegrey
53           54               53       13  sp 006 RSA SPN Brightorangecrust
54           55               17       13                        sp 005 RSA
55           56               36       13                      dellachiajei
57           58               57       13                       magnilarvum
58           59                8       13           sp 008 SPN RSA Peachtip
61           62               61       13    sp 001 RSA SPN Firm dark large
62           63               17       13               sp 002 RSA michaeli
63           64               17       13                       pedunculata
69           70               69       13                           oxitoxa
70           71               25       13                        clathratus
73           74               73       13          sp 001 RSA MKB CRRF mesh

In [1690]:
collection = pd.merge(species_df[['taxonomy_id', 'Species']], collection, on=['Species'])
collection

,taxonomy_id,Species,site_id,sample_id,other_ids,date_collected,permit_no,collected_by,identified_by,classification,...,Subphylum,Class,Subclass,Superorder,Order,Suborder,Family,Subfamily,Genus,Subgenus
0,9,sp 015 RSA SPN roseum,9,TIC2041-1,NaN,30/10/2041,RES2041,Trevor Andrews and Clive Morrison,Clive Morrison,Preliminary,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
1,16,bellae,9,TIC2041-9,NaN,14/01/2041,RES2041,Clive Morrison and Trevor Andrews,Clive Morrison,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN
2,16,bellae,13,TIC2041-2,NaN,21/06/2041,RES2041,Clive Morrison,Clive Morrison,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Cyclacanthia,NaN
3,18,sp 004 RSA nguni,10,TIC2041-5,NaN,05/02/2041,RES2041,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
4,18,sp 004 RSA nguni,11,TIC2041-3,NaN,15/02/2041,RES2041,Trevor Andrews; Mandy Peterson,Harry Warner,Preliminary,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
5,22,sp 001 RSA MH NMMU,15,TIC2041-4,NaN,03/01/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Complete,...,NaN,Demospongiae,NaN,NaN,Dictyoceratida,NaN,Ircinidae,NaN,Psammocinia,NaN
6,26,sp 001 RSA MKB CRRF,14,TIC2041-6,NaN,20/12/2041,RES2041,Clive Morrison,Harry Warner,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN
7,26,sp 001 RSA MKB CRRF,20,SAF43-7,NaN,17/09/2043,RES2043,Mandy Peterson; Trevor Andrews,Clive Morrison,Complete,...,NaN,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Ciocalypta,NaN
8,30,sp 002 RSA SPN CRRF,1,MOZ42-1,NaN,02/04/2042,RES2042,Clive Morrison,Clive Morrison,Preliminary,...,NaN,Demospongiae,NaN,NaN,Halichondrida,NaN,Halichondriidae,NaN,Hymeniacidon,NaN
9,30,sp 002 RSA SPN CRRF,12,TIC2041-7,NaN,10/11/2041,RES2041,Mandy Peterson and Clive Morrison,Harry Warner,Preliminary,...,NaN,Demospongiae,NaN,NaN,Hadromerida,NaN,Clionaidae,NaN,NG Clionaidae 001 RSA MKB CRRF,NaN
10,33,sp001 thick purple fan,16,TIC2041-8,NaN,15/08/2041,RES2041,Trevor Andrews,Clive Morrison,Tentative,...,NaN,Demospongiae,NaN,NaN,Hadromerida,NaN,Hemiasterellidae,NaN,Hemiasterella,NaN
11,34,sp 001 RSA toufieki,1,MOZ42-9,NaN,08/07/2042,RES2042,Mandy Peterson and Clive Morrison,Harry Warner,Complete,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
12,34,sp 001 RSA toufieki,4,MOZ42-7,NaN,09/09/2042,RES2042,Trevor Andrews and Clive Morrison,Harry Warner,Preliminary,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
13,34,sp 001 RSA toufieki,13,TIC2041-10,NaN,18/09/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
14,37,sp 002 RSA SPN Peach pads,11,TIC2041-11,NaN,27/09/2041,RES2041,Trevor Andrews,Clive Morrison,Questionable,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN
15,38,sp 005 SPN RSA Redwhitetongue,3,MOZ42-3,NaN,12/01/2042,RES2042,Clive Morrison,Clive Morrison,Complete,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
16,38,sp 005 SPN RSA Redwhitetongue,15,TIC2041-12,NaN,02/02/2041,RES2041,Clive Morrison,Harry Warner,Tentative,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
17,41,sp 003 RSA SPN Spitspeaks,10,TIC2041-13,NaN,08/02/2041,RES2041,Mandy Peterson; Trevor Andrews,Harry Warner,Questionable,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Atriolum,NaN
18,46,sp 001 RSA MKB CRRF purple,14,TIC2041-14,NaN,25/10/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Complete,...,NaN,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona
19,47,sp 004 RSA SPN blue,12,TIC2041-15,NaN,18/05/2041,RES2041,Mandy Peterson and Clive Morrison,Harry Warner,Complete,...,NaN,Demospongiae,NaN,NaN,Haplosclerida,Haplosclerina,Chalinidae,NaN,Haliclona,Haliclona
20,51,sp 002 SPN RSA Custardbrain,5,MOZ42-2,NaN,07/01/2042,RES2042,Clive Morrison and Mandy Peterson,Clive Morrison,Tentative,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
21,51,sp 002 SPN RSA Custardbrain,7,MOZ42-4,NaN,03/11/2042,RES2042,Clive Morrison,Clive Morrison,Preliminary,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
22,52,sp 003 SPN RSA Gigglegrey,2,MOZ42-5,NaN,07/01/2042,RES2042,Trevor Andrews,Harry Warner,Complete,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
23,54,sp 006 RSA SPN Brightorangecrust,3,MOZ42-11,NaN,30/06/2042,RES2042,Trevor Andrews; Mandy Peterson,Clive Morrison,Complete,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN
24,54,sp 006 RSA SPN Brightorangecrust,6,MOZ42-6,NaN,15/05/2042,RES2042,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Didemnum,NaN
25,55,sp 005 RSA,8,MOZ42-8,NaN,31/08/2042,RES2042,Clive Morrison,Clive Morrison,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
26,56,dellachiajei,5,MOZ42-10,NaN,28/08/2042,RES2042,Clive Morrison and Trevor Andrews,Clive Morrison,Complete,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polycitoridae,NaN,Cystodytes,NaN
27,58,magnilarvum,7,MOZ42-12,NaN,27/02/2042,RES2042,Mandy Peterson,Harry Warner,Complete,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Didemnidae,NaN,Polysyncraton,NaN
28,59,sp 008 SPN RSA Peachtip,2,MOZ42-13,NaN,05/02/2042,RES2042,Trevor Andrews; Mandy Peterson,Harry Warner,Questionable,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Pseudodistomidae,NaN,Pseudodistoma,NaN
29,62,sp 001 RSA SPN Firm dark large,6,MOZ42-14,NaN,13/03/2042,RES2042,Mandy Peterson and Clive Morrison,Clive Morrison,Tentative,...,Urochordata -Tunicata,Ascidiacea,NaN,Enterogona,Aplousobranchia,NaN,Polyclinidae,NaN,Aplidiopsis,NaN
30,63,sp 002 RSA michaeli,1,MOZ42-17,NaN,25/11/2042,RES2042,Mandy Peterson; Trevor Andrews,Clive Morrison,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
31,63,sp 002 RSA michaeli,4,MOZ42-15,NaN,05/10/2042,RES2042,Trevor Andrews; Mandy Peterson,Harry Warner,Preliminary,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
32,63,sp 002 RSA michaeli,8,MOZ42-16,NaN,14/02/2042,RES2042,Clive Morrison,Harry Warner,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
33,63,sp 002 RSA michaeli,17,SAF43-1,NaN,06/01/2043,RES2043,Mandy Peterson,Clive Morrison,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
34,63,sp 002 RSA michaeli,22,SAF43-6,NaN,26/01/2043,RES2043,Mandy Peterson; Trevor Andrews,Harry Warner,Complete,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
35,64,pedunculata,19,SAF43-3,NaN,09/07/2043,RES2043,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
36,64,pedunculata,19,SAF43-11,NaN,27/01/2043,RES2043,Trevor Andrews; Mandy Peterson,Harry Warner,Complete,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
37,64,pedunculata,21,SAF43-2,NaN,15/07/2043,RES2043,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
38,64,pedunculata,21,SAF43-10,NaN,30/06/2043,RES2043,Clive Morrison and Mandy Peterson,Harry Warner,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
39,64,pedunculata,23,SAF43-12,NaN,22/08/2043,RES2043,Mandy Peterson; Trevor Andrews,Harry Warner,Preliminary,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Latrunculina,Latrunculiidae,NaN,Tsitsikamma,NaN
40,70,oxitoxa,23,SAF43-4,NaN,08/12/2043,RES2043,Trevor Andrews; Mandy Peterson,Clive Morrison,Preliminary,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Thalysias
41,71,clathratus,17,SAF43-9,NaN,21/12/2043,RES2043,Mandy Peterson; Trevor Andrews,Clive Morrison,Tentative,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN
42,71,clathratus,18,SAF43-5,NaN,08/04/2043,RES2043,Trevor Andrews; Mandy Peterson,Clive Morrison,Complete,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Myxillina,Hymedesmiidae,NaN,Phorbas,NaN
43,74,sp 001 RSA MKB CRRF mesh,24,SAF43-8,NaN,30/07/2043,RES2043,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,...,NaN,Demospongiae,NaN,NaN,Poecilosclerida,Microcionina,Microcionidae,Microcioninae,Clathria,Axosuberites

In [1691]:
# Remove species information other than taxonomy_id
collection.drop(['Kingdom', 'Phylum', 'Subphylum', 'Class', 'Subclass', 'Superorder', 'Order', 'Suborder', 'Family', 'Subfamily', 'Genus', 'Subgenus', 'Species'], axis=1, inplace=True)
collection

,taxonomy_id,site_id,sample_id,other_ids,date_collected,permit_no,collected_by,identified_by,classification,other_description
0,9,9,TIC2041-1,NaN,30/10/2041,RES2041,Trevor Andrews and Clive Morrison,Clive Morrison,Preliminary,NaN
1,16,9,TIC2041-9,NaN,14/01/2041,RES2041,Clive Morrison and Trevor Andrews,Clive Morrison,Questionable,NaN
2,16,13,TIC2041-2,NaN,21/06/2041,RES2041,Clive Morrison,Clive Morrison,Tentative,NaN
3,18,10,TIC2041-5,NaN,05/02/2041,RES2041,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,NaN
4,18,11,TIC2041-3,NaN,15/02/2041,RES2041,Trevor Andrews; Mandy Peterson,Harry Warner,Preliminary,NaN
5,22,15,TIC2041-4,NaN,03/01/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Complete,NaN
6,26,14,TIC2041-6,NaN,20/12/2041,RES2041,Clive Morrison,Harry Warner,Questionable,NaN
7,26,20,SAF43-7,NaN,17/09/2043,RES2043,Mandy Peterson; Trevor Andrews,Clive Morrison,Complete,NaN
8,30,1,MOZ42-1,NaN,02/04/2042,RES2042,Clive Morrison,Clive Morrison,Preliminary,NaN
9,30,12,TIC2041-7,NaN,10/11/2041,RES2041,Mandy Peterson and Clive Morrison,Harry Warner,Preliminary,NaN
10,33,16,TIC2041-8,NaN,15/08/2041,RES2041,Trevor Andrews,Clive Morrison,Tentative,NaN
11,34,1,MOZ42-9,NaN,08/07/2042,RES2042,Mandy Peterson and Clive Morrison,Harry Warner,Complete,NaN
12,34,4,MOZ42-7,NaN,09/09/2042,RES2042,Trevor Andrews and Clive Morrison,Harry Warner,Preliminary,NaN
13,34,13,TIC2041-10,NaN,18/09/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,NaN
14,37,11,TIC2041-11,NaN,27/09/2041,RES2041,Trevor Andrews,Clive Morrison,Questionable,NaN
15,38,3,MOZ42-3,NaN,12/01/2042,RES2042,Clive Morrison,Clive Morrison,Complete,NaN
16,38,15,TIC2041-12,NaN,02/02/2041,RES2041,Clive Morrison,Harry Warner,Tentative,NaN
17,41,10,TIC2041-13,NaN,08/02/2041,RES2041,Mandy Peterson; Trevor Andrews,Harry Warner,Questionable,NaN
18,46,14,TIC2041-14,NaN,25/10/2041,RES2041,Trevor Andrews and Clive Morrison,Harry Warner,Complete,NaN
19,47,12,TIC2041-15,NaN,18/05/2041,RES2041,Mandy Peterson and Clive Morrison,Harry Warner,Complete,NaN
20,51,5,MOZ42-2,NaN,07/01/2042,RES2042,Clive Morrison and Mandy Peterson,Clive Morrison,Tentative,NaN
21,51,7,MOZ42-4,NaN,03/11/2042,RES2042,Clive Morrison,Clive Morrison,Preliminary,NaN
22,52,2,MOZ42-5,NaN,07/01/2042,RES2042,Trevor Andrews,Harry Warner,Complete,NaN
23,54,3,MOZ42-11,NaN,30/06/2042,RES2042,Trevor Andrews; Mandy Peterson,Clive Morrison,Complete,NaN
24,54,6,MOZ42-6,NaN,15/05/2042,RES2042,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,NaN
25,55,8,MOZ42-8,NaN,31/08/2042,RES2042,Clive Morrison,Clive Morrison,Questionable,NaN
26,56,5,MOZ42-10,NaN,28/08/2042,RES2042,Clive Morrison and Trevor Andrews,Clive Morrison,Complete,NaN
27,58,7,MOZ42-12,NaN,27/02/2042,RES2042,Mandy Peterson,Harry Warner,Complete,NaN
28,59,2,MOZ42-13,NaN,05/02/2042,RES2042,Trevor Andrews; Mandy Peterson,Harry Warner,Questionable,NaN
29,62,6,MOZ42-14,NaN,13/03/2042,RES2042,Mandy Peterson and Clive Morrison,Clive Morrison,Tentative,NaN
30,63,1,MOZ42-17,NaN,25/11/2042,RES2042,Mandy Peterson; Trevor Andrews,Clive Morrison,Tentative,NaN
31,63,4,MOZ42-15,NaN,05/10/2042,RES2042,Trevor Andrews; Mandy Peterson,Harry Warner,Preliminary,NaN
32,63,8,MOZ42-16,NaN,14/02/2042,RES2042,Clive Morrison,Harry Warner,Tentative,NaN
33,63,17,SAF43-1,NaN,06/01/2043,RES2043,Mandy Peterson,Clive Morrison,Questionable,NaN
34,63,22,SAF43-6,NaN,26/01/2043,RES2043,Mandy Peterson; Trevor Andrews,Harry Warner,Complete,NaN
35,64,19,SAF43-3,NaN,09/07/2043,RES2043,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,NaN
36,64,19,SAF43-11,NaN,27/01/2043,RES2043,Trevor Andrews; Mandy Peterson,Harry Warner,Complete,NaN
37,64,21,SAF43-2,NaN,15/07/2043,RES2043,Trevor Andrews and Clive Morrison,Harry Warner,Tentative,NaN
38,64,21,SAF43-10,NaN,30/06/2043,RES2043,Clive Morrison and Mandy Peterson,Harry Warner,Questionable,NaN
39,64,23,SAF43-12,NaN,22/08/2043,RES2043,Mandy Peterson; Trevor Andrews,Harry Warner,Preliminary,NaN
40,70,23,SAF43-4,NaN,08/12/2043,RES2043,Trevor Andrews; Mandy Peterson,Clive Morrison,Preliminary,NaN
41,71,17,SAF43-9,NaN,21/12/2043,RES2043,Mandy Peterson; Trevor Andrews,Clive Morrison,Tentative,NaN
42,71,18,SAF43-5,NaN,08/04/2043,RES2043,Trevor Andrews; Mandy Peterson,Clive Morrison,Complete,NaN
43,74,24,SAF43-8,NaN,30/07/2043,RES2043,Clive Morrison and Mandy Peterson,Clive Morrison,Questionable,NaN

### Person collection table

In [1692]:
people_collector_df = collection[['sample_id', 'collected_by']]
person_collection = pd.DataFrame()
for collector in finalCollectors:
    people = people_collector_df[people_collector_df.collected_by.str.contains(collector, regex=False)]
    people.insert(2, 'person', collector)
    person_collection = person_collection.append(people)

person_collection.insert(3, 'person_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    person_collection.loc[person_collection.person == p, 'person_id'] = pID
person_collection.drop(['collected_by', 'person'], axis=1, inplace=True)
person_collection.rename(columns={'person_id':'user_id'}, inplace=True)
person_collection

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\897392064.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  person_collection = person_collection.append(people)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\897392064.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  person_collection = person_collection.append(people)
C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\897392064.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  person_collection = person_collection.append(people)

    sample_id  user_id
0   TIC2041-1        9
1   TIC2041-9        9
4   TIC2041-3        9
5   TIC2041-4        9
7     SAF43-7        9
..        ...      ...
39   SAF43-12       10
40    SAF43-4       10
41    SAF43-9       10
42    SAF43-5       10
43    SAF43-8       10

[75 rows x 2 columns]

In [1693]:
# Remove collected by from collection table
collection.drop(['collected_by'], axis=1, inplace=True)
collection.insert(7, 'identifier_id', 1)
personIDs = person_df['person_id'].tolist()
names = person_df['full_name'].tolist()

for pID, p in zip(personIDs, names):
    collection.loc[collection.identified_by == p, 'identifier_id'] = pID
collection.drop(['identified_by'], axis=1, inplace=True)

collection['date_collected'] = pd.to_datetime(collection['date_collected'])
collection

C:\Users\Emily\AppData\Local\Temp\ipykernel_26324\1220082095.py:11: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  collection['date_collected'] = pd.to_datetime(collection['date_collected'])

,taxonomy_id,site_id,sample_id,other_ids,date_collected,permit_no,identifier_id,classification,other_description
0,9,9,TIC2041-1,NaN,2041-10-30,RES2041,7,Preliminary,NaN
1,16,9,TIC2041-9,NaN,2041-01-14,RES2041,7,Questionable,NaN
2,16,13,TIC2041-2,NaN,2041-06-21,RES2041,7,Tentative,NaN
3,18,10,TIC2041-5,NaN,2041-05-02,RES2041,7,Questionable,NaN
4,18,11,TIC2041-3,NaN,2041-02-15,RES2041,8,Preliminary,NaN
5,22,15,TIC2041-4,NaN,2041-03-01,RES2041,8,Complete,NaN
6,26,14,TIC2041-6,NaN,2041-12-20,RES2041,8,Questionable,NaN
7,26,20,SAF43-7,NaN,2043-09-17,RES2043,7,Complete,NaN
8,30,1,MOZ42-1,NaN,2042-02-04,RES2042,7,Preliminary,NaN
9,30,12,TIC2041-7,NaN,2041-10-11,RES2041,8,Preliminary,NaN
10,33,16,TIC2041-8,NaN,2041-08-15,RES2041,7,Tentative,NaN
11,34,1,MOZ42-9,NaN,2042-08-07,RES2042,8,Complete,NaN
12,34,4,MOZ42-7,NaN,2042-09-09,RES2042,8,Preliminary,NaN
13,34,13,TIC2041-10,NaN,2041-09-18,RES2041,8,Tentative,NaN
14,37,11,TIC2041-11,NaN,2041-09-27,RES2041,7,Questionable,NaN
15,38,3,MOZ42-3,NaN,2042-12-01,RES2042,7,Complete,NaN
16,38,15,TIC2041-12,NaN,2041-02-02,RES2041,8,Tentative,NaN
17,41,10,TIC2041-13,NaN,2041-08-02,RES2041,8,Questionable,NaN
18,46,14,TIC2041-14,NaN,2041-10-25,RES2041,8,Complete,NaN
19,47,12,TIC2041-15,NaN,2041-05-18,RES2041,8,Complete,NaN
20,51,5,MOZ42-2,NaN,2042-07-01,RES2042,7,Tentative,NaN
21,51,7,MOZ42-4,NaN,2042-03-11,RES2042,7,Preliminary,NaN
22,52,2,MOZ42-5,NaN,2042-07-01,RES2042,8,Complete,NaN
23,54,3,MOZ42-11,NaN,2042-06-30,RES2042,7,Complete,NaN
24,54,6,MOZ42-6,NaN,2042-05-15,RES2042,7,Questionable,NaN
25,55,8,MOZ42-8,NaN,2042-08-31,RES2042,7,Questionable,NaN
26,56,5,MOZ42-10,NaN,2042-08-28,RES2042,7,Complete,NaN
27,58,7,MOZ42-12,NaN,2042-02-27,RES2042,8,Complete,NaN
28,59,2,MOZ42-13,NaN,2042-05-02,RES2042,8,Questionable,NaN
29,62,6,MOZ42-14,NaN,2042-03-13,RES2042,7,Tentative,NaN
30,63,1,MOZ42-17,NaN,2042-11-25,RES2042,7,Tentative,NaN
31,63,4,MOZ42-15,NaN,2042-05-10,RES2042,8,Preliminary,NaN
32,63,8,MOZ42-16,NaN,2042-02-14,RES2042,8,Tentative,NaN
33,63,17,SAF43-1,NaN,2043-06-01,RES2043,7,Questionable,NaN
34,63,22,SAF43-6,NaN,2043-01-26,RES2043,8,Complete,NaN
35,64,19,SAF43-3,NaN,2043-09-07,RES2043,8,Tentative,NaN
36,64,19,SAF43-11,NaN,2043-01-27,RES2043,8,Complete,NaN
37,64,21,SAF43-2,NaN,2043-07-15,RES2043,8,Tentative,NaN
38,64,21,SAF43-10,NaN,2043-06-30,RES2043,8,Questionable,NaN
39,64,23,SAF43-12,NaN,2043-08-22,RES2043,8,Preliminary,NaN
40,70,23,SAF43-4,NaN,2043-08-12,RES2043,7,Preliminary,NaN
41,71,17,SAF43-9,NaN,2043-12-21,RES2043,7,Tentative,NaN
42,71,18,SAF43-5,NaN,2043-08-04,RES2043,7,Complete,NaN
43,74,24,SAF43-8,NaN,2043-07-30,RES2043,7,Questionable,NaN

### Strain Table

In [1694]:
strain_df = pd.read_excel("strain.xlsx")
strainSpecies = species_df.reset_index(drop=True)
strainSpecies = strainSpecies.iloc[:len(strain_df), :]
strain_df = pd.concat([strain_df, strainSpecies], axis=1)
strain_df.rename(columns={'supplierID':'strain_id', 'cultivationMedia':'cultivation_media'}, inplace=True)
strain_df.drop(['parent_taxon_id', 'rank_id', 'Species'], axis=1, inplace=True)
strain_df

   strain_id cultivation_media  taxonomy_id
0      AAP_1               PDM            9
1      AAP_2               PDM           16
2      AAP_3               PDM           18
3      AAP_4               WYM           22
4      AAP_5               PDM           26
5      AAP_6               MEM           30
6      AAP_7           PDM+I/O           33
7      AAP_8               MEM           34
8      AAP_9               PDM           37
9     AAP_10               PDM           38
10    AAP_11               PDM           41
11    AAP_12           PDM+I/O           46
12    AAP_13           PDM+I/O           47
13    AAP_14               MEM           51
14    AAP_15               PDM           52
15    AAP_16               WYM           54
16    AAP_17           PDM+I/O           55
17    AAP_18               PDM           56

In [1695]:
# Send role table to mysql
hostname = "localhost"
dbname = "addhubproject"
uname = "root"
pwd = ""

engine = create_engine("mysql://{user}:{pw}@{host}/{db}".format(host=hostname, db=dbname, user=uname, pw=pwd))

# nmr.to_sql('nmr', engine, index=False)

# role_df.to_sql('role', engine, index=False)

# Export extract dataframe to extracts table

# role_df.to_sql('roles', engine, if_exists='append', index=False)
# person_role_df.to_sql('role_users', engine, if_exists='append', index=False)
# group_df.to_sql('groups', engine, if_exists='append', index=False)
# extract.to_sql('extracts', engine, if_exists='append', index=False)
# fraction.to_sql('fractions', engine, if_exists='append', index=False)
# derivedpurecomp.to_sql('derivedpurecomps', engine, if_exists='append', index=False)
# process.drop(['destination_of_sample'], axis=1, inplace=True)
# process.to_sql('processes', engine, if_exists='append', index=False)
# newms.to_sql('massspecs', engine, if_exists='append', index=False)
# newnmr.to_sql('nmrs', engine, if_exists='append', index=False)
# bioassay_df.to_sql('bioassays', engine, if_exists='append', index=False)
# countries_df.to_sql('countries', engine, if_exists='append', index=False)
# regions_df.to_sql('regions', engine, if_exists='append', index=False)
# city_df.to_sql('cities', engine, if_exists='append', index=False)
# localarea_df.to_sql('localareas', engine, if_exists='append', index=False)
# station_df.to_sql('stations', engine, if_exists='append', index=False)
# site_df.to_sql('sites', engine, if_exists='append', index=False)
# taxonhierarcy.to_sql('taxonhierarchies', engine, if_exists='append', index=False)
# taxonomy.to_sql('taxonomies', engine, if_exists='append', index=False)
# collection.to_sql('collections', engine, if_exists='append', index=False)
# person_collection.to_sql('collection_users', engine, if_exists='append', index=False)
# strain_df.to_sql('strains', engine, if_exists='append', index=False)
# lcms_records.to_sql('hplcrequests', engine, if_exists='append', index=False)

116